-- ============================================================================
-- Migration: Task 4 - Complete Layout Artifact Graph Schema
-- ============================================================================
-- This migration defines the persistent SQL schema for the CandidateArtifactGraph
-- and all entity types generated by ML algorithms.
--
-- Principles:
-- 1. All entity IDs are UUIDs (PRIMARY KEY type UUID)
-- 2. Foreign keys are enforced at schema level (ON DELETE CASCADE)
-- 3. Indexes on high-query-volume columns (status, optimization_run_id)
-- 4. Checksum column for reproducibility verification
-- 5. Lineage tracking preserved (created_by, optimization_run_id, parent_candidate_id)
-- ============================================================================

-- Create schema for artifact graph entities
CREATE SCHEMA IF NOT EXISTS ml_artifacts;

-- ============================================================================
-- Candidate Artifact Graph (Header Table)
-- ============================================================================
CREATE TABLE ml_artifacts.candidate_artifact_graphs (
    layout_id UUID PRIMARY KEY,
    project_id UUID NOT NULL,
    version VARCHAR(16) NOT NULL DEFAULT '1.0',
    
    -- Lineage
    checksum VARCHAR(64) NOT NULL UNIQUE,  -- SHA256 hex string
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_project FOREIGN KEY (project_id) 
        REFERENCES public.projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_graph_project ON ml_artifacts.candidate_artifact_graphs(project_id);
CREATE INDEX idx_graph_checksum ON ml_artifacts.candidate_artifact_graphs(checksum);

-- ============================================================================
-- Solar Panels (Entity Layer 1)
-- ============================================================================
CREATE TABLE ml_artifacts.solar_panels (
    panel_id UUID PRIMARY KEY,
    layout_id UUID NOT NULL,
    asset_id UUID NOT NULL,
    tile_id UUID NOT NULL,
    string_id UUID,  -- FK to panel_strings (nullable during ML phase)
    
    -- Geometry (WGS84 / EPSG:4326)
    -- Stored as GeoJSON for PostGIS querying
    geometry JSONB NOT NULL,  -- {vertices: [{lon, lat, elev_m}, ...], elevation_source, datum_offset_m}
    geometry_geom GEOMETRY(POLYGON, 4326) GENERATED ALWAYS AS 
        (ST_GeomFromGeoJSON(geometry->>'geometry_geom')) STORED,
    
    -- Orientation
    tilt_degrees NUMERIC(5, 2) NOT NULL CHECK (tilt_degrees >= 0 AND tilt_degrees <= 90),
    azimuth_degrees NUMERIC(6, 2) NOT NULL CHECK (azimuth_degrees >= 0 AND azimuth_degrees < 360),
    
    -- Precision
    layout_score NUMERIC(4, 3) NOT NULL CHECK (layout_score >= 0 AND layout_score <= 1),
    mpp_capacity_kw NUMERIC(10, 3) NOT NULL,
    shading_factor NUMERIC(4, 3) NOT NULL CHECK (shading_factor >= 0 AND shading_factor <= 1),
    
    -- Lineage
    created_by VARCHAR(32) NOT NULL,  -- "deterministic_synthesis", "ml_optimization", "user_manual"
    optimization_run_id UUID,
    parent_candidate_id UUID,
    
    -- Feasibility
    feasibility_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',  -- PENDING, VALID, INVALID, UNVALIDATED
    feasibility_reason TEXT,
    
    -- Precision metadata (JSONB for flexibility)
    precision_metadata JSONB,
    
    -- Audit
    checksum VARCHAR(64) NOT NULL,  -- SHA256
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_layout FOREIGN KEY (layout_id) 
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE,
    CONSTRAINT fk_asset FOREIGN KEY (asset_id)
        REFERENCES public.assets(id) ON DELETE RESTRICT,
    CONSTRAINT fk_parent_candidate FOREIGN KEY (parent_candidate_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE SET NULL
);

CREATE INDEX idx_panels_layout ON ml_artifacts.solar_panels(layout_id);
CREATE INDEX idx_panels_string ON ml_artifacts.solar_panels(string_id);
CREATE INDEX idx_panels_optimization_run ON ml_artifacts.solar_panels(optimization_run_id);
CREATE INDEX idx_panels_feasibility ON ml_artifacts.solar_panels(feasibility_status);
CREATE INDEX idx_panels_geometry ON ml_artifacts.solar_panels USING GIST (geometry_geom);

-- ============================================================================
-- Panel Strings (Entity Layer 2)
-- ============================================================================
CREATE TABLE ml_artifacts.panel_strings (
    string_id UUID PRIMARY KEY,
    layout_id UUID NOT NULL,
    network_id UUID,  -- FK to electrical networks (nullable during ML phase)
    inverter_group_id UUID,  -- FK to inverter_groups (assigned later)
    
    -- Composition
    panel_ids UUID[] NOT NULL,  -- Array of solar panel UUIDs
    panel_count INTEGER NOT NULL CHECK (panel_count > 0),
    mppt_index INT,
    
    -- Electrical attributes
    string_voltage_vdc NUMERIC(10, 2) NOT NULL,
    string_current_adc NUMERIC(10, 2) NOT NULL,
    string_power_kw NUMERIC(10, 3) NOT NULL,
    
    -- Feasibility
    feasibility_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    feasibility_reason TEXT,
    
    -- Lineage
    created_by VARCHAR(32) NOT NULL,
    optimization_run_id UUID,
    
    -- Precision metadata
    precision_metadata JSONB,
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_layout FOREIGN KEY (layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE
);

CREATE INDEX idx_strings_layout ON ml_artifacts.panel_strings(layout_id);
CREATE INDEX idx_strings_inverter_group ON ml_artifacts.panel_strings(inverter_group_id);
CREATE INDEX idx_strings_optimization_run ON ml_artifacts.panel_strings(optimization_run_id);
CREATE INDEX idx_strings_feasibility ON ml_artifacts.panel_strings(feasibility_status);

-- ============================================================================
-- Inverter Groups (Entity Layer 2)
-- ============================================================================
CREATE TABLE ml_artifacts.inverter_groups (
    inverter_group_id UUID PRIMARY KEY,
    layout_id UUID NOT NULL,
    network_id UUID,  -- FK to electrical networks
    inverter_asset_id UUID NOT NULL,
    
    -- Composition
    string_ids UUID[] NOT NULL,  -- Array of string UUIDs
    string_count INTEGER NOT NULL CHECK (string_count > 0),
    
    -- Siting (WGS84)
    position JSONB NOT NULL,  -- {longitude, latitude, elevation_m}
    position_geom GEOMETRY(POINT, 4326) GENERATED ALWAYS AS
        (ST_Point((position->>'longitude')::float8, (position->>'latitude')::float8, 4326)) STORED,
    position_snapped_to_feature VARCHAR(32),  -- "road", "foundation", "building"
    
    -- Electrical
    dc_input_kw NUMERIC(10, 3) NOT NULL,
    ac_output_kw NUMERIC(10, 3) NOT NULL,
    dc_ac_ratio NUMERIC(4, 3) NOT NULL CHECK (dc_ac_ratio > 0),
    efficiency_pct NUMERIC(5, 2) NOT NULL CHECK (efficiency_pct >= 0 AND efficiency_pct <= 100),
    
    -- Feasibility
    feasibility_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    feasibility_reason TEXT,
    
    -- Lineage
    created_by VARCHAR(32) NOT NULL,
    optimization_run_id UUID,
    
    -- Precision metadata
    precision_metadata JSONB,
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_layout FOREIGN KEY (layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE,
    CONSTRAINT fk_asset FOREIGN KEY (inverter_asset_id)
        REFERENCES public.assets(id) ON DELETE RESTRICT
);

CREATE INDEX idx_inverters_layout ON ml_artifacts.inverter_groups(layout_id);
CREATE INDEX idx_inverters_optimization_run ON ml_artifacts.inverter_groups(optimization_run_id);
CREATE INDEX idx_inverters_feasibility ON ml_artifacts.inverter_groups(feasibility_status);
CREATE INDEX idx_inverters_position ON ml_artifacts.inverter_groups USING GIST (position_geom);

-- ============================================================================
-- Transformer Nodes (Entity Layer 2)
-- ============================================================================
CREATE TABLE ml_artifacts.transformer_nodes (
    transformer_id UUID PRIMARY KEY,
    layout_id UUID NOT NULL,
    transformer_asset_id UUID NOT NULL,
    
    -- Siting (WGS84)
    position JSONB NOT NULL,  -- {longitude, latitude, elevation_m}
    position_geom GEOMETRY(POINT, 4326) GENERATED ALWAYS AS
        (ST_Point((position->>'longitude')::float8, (position->>'latitude')::float8, 4326)) STORED,
    position_snapped_to_feature VARCHAR(32),
    
    -- Electrical
    primary_voltage_kv NUMERIC(8, 2) NOT NULL,
    secondary_voltage_kv NUMERIC(8, 2) NOT NULL,
    kva_rating NUMERIC(12, 2) NOT NULL,
    
    -- Network connectivity
    connected_inverter_group_ids UUID[] NOT NULL,  -- Array of inverter group UUIDs
    load_kva NUMERIC(12, 2) NOT NULL,
    load_utilization_pct NUMERIC(5, 2) NOT NULL CHECK (load_utilization_pct >= 0 AND load_utilization_pct <= 100),
    
    -- Feasibility
    feasibility_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    feasibility_reason TEXT,
    
    -- Lineage
    created_by VARCHAR(32) NOT NULL,
    optimization_run_id UUID,
    
    -- Precision metadata
    precision_metadata JSONB,
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_layout FOREIGN KEY (layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE,
    CONSTRAINT fk_asset FOREIGN KEY (transformer_asset_id)
        REFERENCES public.assets(id) ON DELETE RESTRICT
);

CREATE INDEX idx_transformers_layout ON ml_artifacts.transformer_nodes(layout_id);
CREATE INDEX idx_transformers_optimization_run ON ml_artifacts.transformer_nodes(optimization_run_id);
CREATE INDEX idx_transformers_feasibility ON ml_artifacts.transformer_nodes(feasibility_status);
CREATE INDEX idx_transformers_position ON ml_artifacts.transformer_nodes USING GIST (position_geom);

-- ============================================================================
-- Cable Corridor Segments (Entity Layer 3)
-- ============================================================================
CREATE TABLE ml_artifacts.cable_corridor_segments (
    corridor_id UUID PRIMARY KEY,
    layout_id UUID NOT NULL,
    
    -- Routing
    path JSONB NOT NULL,  -- {vertices: [{lon, lat, elev_m}, ...], length_m, height_profile}
    path_geom GEOMETRY(LINESTRING, 4326) GENERATED ALWAYS AS
        (ST_LineFromText((path->>'path_wkt'), 4326)) STORED,
    length_m NUMERIC(12, 2) NOT NULL,
    height_profile VARCHAR(32),  -- "flat", "hilly", "mountainous"
    
    -- Cable specification
    cable_type VARCHAR(16) NOT NULL,  -- "UG_DC", "UG_AC", etc.
    conductor_count INTEGER NOT NULL CHECK (conductor_count > 0),
    conductor_size_mm2 NUMERIC(8, 2) NOT NULL,
    
    -- Network role
    source_location_type VARCHAR(32) NOT NULL,  -- "inverter_group", "combiner_box", etc.
    source_location_entity_id UUID NOT NULL,
    target_location_type VARCHAR(32) NOT NULL,
    target_location_entity_id UUID,
    
    -- Electrical constraints
    current_rating_adc NUMERIC(10, 2) NOT NULL,
    voltage_drop_v NUMERIC(8, 2) NOT NULL,
    
    -- Feasibility
    feasibility_status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    feasibility_reason TEXT,
    
    -- BoM
    bom_count_m NUMERIC(12, 2) NOT NULL,
    
    -- Lineage
    created_by VARCHAR(32) NOT NULL,
    optimization_run_id UUID,
    
    -- Precision metadata
    precision_metadata JSONB,
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_layout FOREIGN KEY (layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE
);

CREATE INDEX idx_cables_layout ON ml_artifacts.cable_corridor_segments(layout_id);
CREATE INDEX idx_cables_optimization_run ON ml_artifacts.cable_corridor_segments(optimization_run_id);
CREATE INDEX idx_cables_feasibility ON ml_artifacts.cable_corridor_segments(feasibility_status);
CREATE INDEX idx_cables_path ON ml_artifacts.cable_corridor_segments USING GIST (path_geom);

-- ============================================================================
-- Fault Identifiers (Entity Layer 3)
-- ============================================================================
CREATE TABLE ml_artifacts.fault_identifiers (
    fault_id UUID PRIMARY KEY,
    layout_id UUID NOT NULL,
    
    -- Location and scope
    position JSONB NOT NULL,  -- {longitude, latitude, elevation_m}
    position_geom GEOMETRY(POINT, 4326) GENERATED ALWAYS AS
        (ST_Point((position->>'longitude')::float8, (position->>'latitude')::float8, 4326)) STORED,
    scope VARCHAR(32) NOT NULL,  -- "string_combiner", "inverter_protection", etc.
    
    -- Fault chain (upstream entities)
    affected_string_ids UUID[],
    affected_inverter_ids UUID[],
    affected_transformer_ids UUID[],
    
    -- Protection device
    protection_type VARCHAR(32) NOT NULL,
    protection_asset_id UUID,
    
    -- Fault scenario
    fault_scenario VARCHAR(32) NOT NULL,
    detection_method VARCHAR(32) NOT NULL,
    isolation_time_ms NUMERIC(8, 2) NOT NULL,
    
    -- Lineage
    created_by VARCHAR(32) NOT NULL,
    optimization_run_id UUID,
    
    -- Precision metadata
    precision_metadata JSONB,
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_layout FOREIGN KEY (layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE
);

CREATE INDEX idx_faults_layout ON ml_artifacts.fault_identifiers(layout_id);
CREATE INDEX idx_faults_optimization_run ON ml_artifacts.fault_identifiers(optimization_run_id);
CREATE INDEX idx_faults_position ON ml_artifacts.fault_identifiers USING GIST (position_geom);

-- ============================================================================
-- Candidate Lineage (Audit Trail)
-- ============================================================================
CREATE TABLE ml_artifacts.candidate_lineage (
    layout_id UUID PRIMARY KEY,
    
    -- Lineage history
    root_candidate_ids UUID[],
    final_selection_reason TEXT NOT NULL,
    checksum VARCHAR(64) NOT NULL,
    
    -- Optimization history (JSONB array for flexibility)
    optimization_history JSONB NOT NULL DEFAULT '[]',  -- [{run_id, algorithm_name, generation_count, pareto_improvement_pct, completed_at}, ...]
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_layout FOREIGN KEY (layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE
);

-- ============================================================================
-- ML Output Results (Ranking and Scoring)
-- ============================================================================
CREATE TABLE ml_artifacts.ml_candidates (
    candidate_id UUID PRIMARY KEY,
    layout_id UUID NOT NULL,
    project_id UUID NOT NULL,
    experiment_id UUID NOT NULL,
    
    -- Artifact graph foreign key
    artifact_graph_layout_id UUID NOT NULL,
    
    -- Objective scores (JSONB for variable objectives)
    objective_scores JSONB NOT NULL,  -- {feasibility: 0.95, mw_fit: 0.88, ...}
    
    -- Ranking
    composite_score NUMERIC(4, 3) NOT NULL CHECK (composite_score >= 0 AND composite_score <= 1),
    rank INTEGER NOT NULL CHECK (rank > 0),
    
    -- Confidence
    confidence_lower_bound NUMERIC(4, 3),
    confidence_upper_bound NUMERIC(4, 3),
    
    -- Explainability
    selection_reasoning TEXT NOT NULL,
    parent_candidate_ids UUID[],
    optimization_algorithm_used VARCHAR(64),
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_layout FOREIGN KEY (layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE,
    CONSTRAINT fk_artifact_graph FOREIGN KEY (artifact_graph_layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE,
    CONSTRAINT fk_project FOREIGN KEY (project_id)
        REFERENCES public.projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_ml_candidates_experiment ON ml_artifacts.ml_candidates(experiment_id);
CREATE INDEX idx_ml_candidates_layout ON ml_artifacts.ml_candidates(layout_id);
CREATE INDEX idx_ml_candidates_project ON ml_artifacts.ml_candidates(project_id);
CREATE INDEX idx_ml_candidates_rank ON ml_artifacts.ml_candidates(rank);
CREATE INDEX idx_ml_candidates_composite_score ON ml_artifacts.ml_candidates(composite_score DESC);

-- ============================================================================
-- ML Experiment Metadata (Execution Tracking)
-- ============================================================================
CREATE TABLE ml_artifacts.ml_experiments (
    experiment_id UUID PRIMARY KEY,
    project_id UUID NOT NULL,
    layout_id UUID NOT NULL,
    
    -- Execution metadata
    algorithm_name VARCHAR(64) NOT NULL,
    iteration_count INTEGER NOT NULL,
    total_generated INTEGER NOT NULL,
    total_feasible INTEGER NOT NULL,
    total_ranked INTEGER NOT NULL,
    
    -- Timing
    execution_time_ms BIGINT NOT NULL,
    deterministic_fallback_included BOOLEAN NOT NULL DEFAULT FALSE,
    
    -- Audit
    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_project FOREIGN KEY (project_id)
        REFERENCES public.projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_layout FOREIGN KEY (layout_id)
        REFERENCES ml_artifacts.candidate_artifact_graphs(layout_id) ON DELETE CASCADE
);

CREATE INDEX idx_experiments_project ON ml_artifacts.ml_experiments(project_id);
CREATE INDEX idx_experiments_layout ON ml_artifacts.ml_experiments(layout_id);
CREATE INDEX idx_experiments_algorithm ON ml_artifacts.ml_experiments(algorithm_name);

-- ============================================================================
-- Constraints and Objectives Reference (Frozen from Task 3)
-- ============================================================================
CREATE TABLE ml_artifacts.optimization_specs (
    project_id UUID PRIMARY KEY,
    
    -- Version
    version VARCHAR(16) NOT NULL DEFAULT '1.0',
    
    -- Constraints and objectives (JSONB for flexibility)
    hard_constraints JSONB NOT NULL,
    soft_constraints JSONB NOT NULL,
    objectives JSONB NOT NULL,
    
    -- Priority ordering
    lexicographic_priority_order TEXT,
    
    -- Audit
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    
    CONSTRAINT fk_project FOREIGN KEY (project_id)
        REFERENCES public.projects(id) ON DELETE CASCADE
);

-- ============================================================================
-- Grants (if using role-based access control)
-- ============================================================================
-- GRANT SELECT ON ALL TABLES IN SCHEMA ml_artifacts TO readonly_role;
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA ml_artifacts TO ml_service_role;

-- ============================================================================
-- Migration Metadata (for schema versioning)
-- ============================================================================
-- Deferred FK constraints to resolve forward references in table creation order
ALTER TABLE ml_artifacts.solar_panels
    ADD CONSTRAINT fk_string FOREIGN KEY (string_id)
        REFERENCES ml_artifacts.panel_strings(string_id) ON DELETE SET NULL;

ALTER TABLE ml_artifacts.panel_strings
    ADD CONSTRAINT fk_inverter_group FOREIGN KEY (inverter_group_id)
        REFERENCES ml_artifacts.inverter_groups(inverter_group_id) ON DELETE SET NULL;

