package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"testing"
	"time"

	"github.com/google/uuid"
)

const (
	defaultTimeout = 30 * time.Second
)

// SmokeTestConfig holds configuration for smoke tests
type SmokeTestConfig struct {
	APIGatewayURL      string
	ProjectServiceURL  string
	DrawingRevisionURL string
	CADCoreURL         string
	MaxRetries         int
	RetryDelayMs       int
}

// LoadConfig loads smoke test configuration from environment
func LoadConfig() *SmokeTestConfig {
	return &SmokeTestConfig{
		APIGatewayURL:      getEnv("API_GATEWAY_URL", "http://localhost:8090"),
		ProjectServiceURL:  getEnv("PROJECT_SERVICE_URL", "http://localhost:8080"),
		DrawingRevisionURL: getEnv("DRAWING_REVISION_URL", "http://localhost:8088"),
		CADCoreURL:         getEnv("CAD_CORE_URL", "http://localhost:8089"),
		MaxRetries:         5,
		RetryDelayMs:       1000,
	}
}

func getEnv(key, defaultVal string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return defaultVal
}

// HealthCheck verifies service is ready
func HealthCheck(url string) error {
	client := &http.Client{Timeout: 5 * time.Second}
	resp, err := client.Get(url + "/healthz")
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("health check failed with status %d", resp.StatusCode)
	}
	return nil
}

// WaitForService retries health checks until service is ready
func WaitForService(url string, maxRetries int, delayMs int) error {
	for i := 0; i < maxRetries; i++ {
		if err := HealthCheck(url); err == nil {
			return nil
		}
		if i < maxRetries-1 {
			time.Sleep(time.Duration(delayMs) * time.Millisecond)
		}
	}
	return fmt.Errorf("service %s not ready after %d retries", url, maxRetries)
}

// Project represents a solar project
type Project struct {
	ID               string  `json:"id"`
	Name             string  `json:"name"`
	Description      string  `json:"description"`
	Status           string  `json:"status"`
	TargetCapacityMW float64 `json:"target_capacity_mw"`
	ClientName       string  `json:"client_name"`
	CreatedAt        string  `json:"created_at"`
}

// Drawing represents a CAD drawing
type Drawing struct {
	DrawingID         string `json:"drawing_id"`
	ProjectID         string `json:"project_id"`
	Name              string `json:"name"`
	Description       string `json:"description"`
	Status            string `json:"status"`
	CurrentRevisionID string `json:"current_revision_id"`
	RevisionCount     int    `json:"revision_count"`
	EntityCount       int    `json:"entity_count"`
	CreatedAt         string `json:"created_at"`
}

// DrawingCommand represents a mutation to apply to a drawing
type DrawingCommand struct {
	CommandID string      `json:"command_id"`
	DrawingID string      `json:"drawing_id"`
	Actor     string      `json:"actor"`
	Mutations []Mutation  `json:"mutations"`
	Contract  interface{} `json:"contract"`
}

// Mutation represents a single entity mutation (CREATE/UPDATE/DELETE)
type Mutation struct {
	Operation string      `json:"operation"`
	After     interface{} `json:"after,omitempty"`
}

// TestSmokeFullE2E runs the complete end-to-end smoke test
func TestSmokeFullE2E(t *testing.T) {
	cfg := LoadConfig()

	fmt.Println("=== SMOKE TEST: Full E2E Workflow ===")
	fmt.Printf("API Gateway: %s\n", cfg.APIGatewayURL)
	fmt.Printf("Project Service: %s\n", cfg.ProjectServiceURL)
	fmt.Printf("Drawing Revision: %s\n", cfg.DrawingRevisionURL)
	fmt.Printf("CAD Core: %s\n\n", cfg.CADCoreURL)

	// Step 1: Wait for all services
	fmt.Println("[1] Waiting for services to be ready...")
	if err := WaitForService(cfg.ProjectServiceURL, cfg.MaxRetries, cfg.RetryDelayMs); err != nil {
		t.Fatalf("Project Service not ready: %v", err)
	}
	if err := WaitForService(cfg.DrawingRevisionURL, cfg.MaxRetries, cfg.RetryDelayMs); err != nil {
		t.Fatalf("Drawing Revision Service not ready: %v", err)
	}
	if err := WaitForService(cfg.CADCoreURL, cfg.MaxRetries, cfg.RetryDelayMs); err != nil {
		t.Fatalf("CAD Core Service not ready: %v", err)
	}
	if err := WaitForService(cfg.APIGatewayURL, cfg.MaxRetries, cfg.RetryDelayMs); err != nil {
		t.Fatalf("API Gateway not ready: %v", err)
	}
	fmt.Println("✓ All services ready\n")

	// Step 2: Create project via Project Service
	fmt.Println("[2] Creating project...")
	projectID := uuid.NewString()
	projectReq := map[string]interface{}{
		"id":                 projectID,
		"name":               "E2E Test Project",
		"description":        "Generated by smoke test",
		"target_capacity_mw": 5.0,
		"client_name":        "Test Client",
	}
	project := createProject(t, cfg, projectReq)
	if project.ID != projectID {
		t.Errorf("Project ID mismatch: expected %s, got %s", projectID, project.ID)
	}
	fmt.Printf("✓ Project created: %s (%s)\n\n", project.ID, project.Name)

	// Step 3: Create drawing via API Gateway
	fmt.Println("[3] Creating drawing...")
	drawingReq := map[string]interface{}{
		"name":          "Floor Plan",
		"description":   "Building floor plan",
		"author":        "smoke-test@local",
		"metadata_json": "{\"version\":\"1.0\"}",
	}
	drawing := createDrawing(t, cfg, projectID, drawingReq)
	if drawing.ProjectID != projectID {
		t.Errorf("Drawing project ID mismatch: expected %s, got %s", projectID, drawing.ProjectID)
	}
	fmt.Printf("✓ Drawing created: %s\n", drawing.DrawingID)
	fmt.Printf("  - Name: %s\n", drawing.Name)
	fmt.Printf("  - Status: %s\n", drawing.Status)
	fmt.Printf("  - Current Revision: %s\n\n", drawing.CurrentRevisionID)

	// Step 4: Commit drawing command via API Gateway (through CAD Core)
	fmt.Println("[4] Committing drawing command...")
	cmd := DrawingCommand{
		CommandID: uuid.NewString(),
		DrawingID: drawing.DrawingID,
		Actor:     "smoke-test@local",
		Mutations: []Mutation{
			{
				Operation: "CREATE",
				After: map[string]interface{}{
					"entity_id":   uuid.NewString(),
					"entity_type": "POLYLINE",
					"layer_id":    "layer-0",
					"geometry": map[string]interface{}{
						"vertices": []map[string]float64{
							{"x": 0.0, "y": 0.0},
							{"x": 10.0, "y": 0.0},
							{"x": 10.0, "y": 10.0},
							{"x": 0.0, "y": 10.0},
						},
					},
				},
			},
		},
		Contract: map[string]string{"schema_version": "1.0"},
	}
	commitResult := commitCommand(t, cfg, drawing.DrawingID, cmd)
	if commitResult == nil {
		t.Fatal("Commit command failed: no result returned")
	}
	fmt.Printf("✓ Command committed successfully\n")
	fmt.Printf("  - Command ID: %s\n", cmd.CommandID)
	fmt.Printf("  - New Revision ID: %s\n\n", commitResult["revision_id"])

	// Step 5: Get drawing state to verify update
	fmt.Println("[5] Verifying drawing state...")
	updatedDrawing := getDrawing(t, cfg, drawing.DrawingID)
	if updatedDrawing.RevisionCount <= 1 {
		t.Errorf("Revision count should be > 1, got %d", updatedDrawing.RevisionCount)
	}
	if updatedDrawing.EntityCount != 1 {
		t.Errorf("Entity count should be 1, got %d", updatedDrawing.EntityCount)
	}
	fmt.Printf("✓ Drawing state verified\n")
	fmt.Printf("  - Revision Count: %d (expected > 1)\n", updatedDrawing.RevisionCount)
	fmt.Printf("  - Entity Count: %d (expected 1)\n\n", updatedDrawing.EntityCount)

	// Step 6: List drawings in project
	fmt.Println("[6] Listing drawings in project...")
	drawings := listDrawings(t, cfg, projectID)
	if len(drawings) < 1 {
		t.Errorf("Expected at least 1 drawing, got %d", len(drawings))
	}
	found := false
	for _, d := range drawings {
		if d.DrawingID == drawing.DrawingID {
			found = true
			break
		}
	}
	if !found {
		t.Errorf("Created drawing not found in list")
	}
	fmt.Printf("✓ Found %d drawing(s) in project\n\n", len(drawings))

	fmt.Println("=== SMOKE TEST PASSED ===")
}

// createProject creates a project via Project Service
func createProject(t *testing.T, cfg *SmokeTestConfig, req map[string]interface{}) *Project {
	body, err := json.Marshal(req)
	if err != nil {
		t.Fatalf("Failed to marshal project request: %v", err)
	}

	httpReq, err := http.NewRequestWithContext(
		context.Background(),
		"POST",
		cfg.ProjectServiceURL+"/projects",
		bytes.NewReader(body),
	)
	if err != nil {
		t.Fatalf("Failed to create project request: %v", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: defaultTimeout}
	resp, err := client.Do(httpReq)
	if err != nil {
		t.Fatalf("Failed to create project: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		bodyBytes, _ := io.ReadAll(resp.Body)
		t.Fatalf("Create project failed with status %d: %s", resp.StatusCode, string(bodyBytes))
	}

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		t.Fatalf("Failed to decode project response: %v", err)
	}

	return &Project{
		ID:          result["id"].(string),
		Name:        result["name"].(string),
		Description: result["description"].(string),
		Status:      result["status"].(string),
		CreatedAt:   result["created_at"].(string),
	}
}

// createDrawing creates a drawing via API Gateway
func createDrawing(t *testing.T, cfg *SmokeTestConfig, projectID string, req map[string]interface{}) *Drawing {
	body, err := json.Marshal(req)
	if err != nil {
		t.Fatalf("Failed to marshal drawing request: %v", err)
	}

	url := fmt.Sprintf("%s/api/v1/workspace/projects/%s/drawings", cfg.APIGatewayURL, projectID)
	httpReq, err := http.NewRequestWithContext(
		context.Background(),
		"POST",
		url,
		bytes.NewReader(body),
	)
	if err != nil {
		t.Fatalf("Failed to create drawing request: %v", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: defaultTimeout}
	resp, err := client.Do(httpReq)
	if err != nil {
		t.Fatalf("Failed to create drawing: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusCreated {
		bodyBytes, _ := io.ReadAll(resp.Body)
		t.Fatalf("Create drawing failed with status %d: %s", resp.StatusCode, string(bodyBytes))
	}

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		t.Fatalf("Failed to decode drawing response: %v", err)
	}

	drawing := result["drawing"].(map[string]interface{})
	return &Drawing{
		DrawingID:         drawing["drawing_id"].(string),
		ProjectID:         drawing["project_id"].(string),
		Name:              drawing["name"].(string),
		Description:       drawing["description"].(string),
		Status:            drawing["status"].(string),
		CurrentRevisionID: drawing["current_revision_id"].(string),
		RevisionCount:     int(drawing["revision_count"].(float64)),
		EntityCount:       int(drawing["entity_count"].(float64)),
		CreatedAt:         drawing["created_at"].(string),
	}
}

// getDrawing retrieves a drawing via API Gateway
func getDrawing(t *testing.T, cfg *SmokeTestConfig, drawingID string) *Drawing {
	url := fmt.Sprintf("%s/api/v1/workspace/drawings/%s", cfg.APIGatewayURL, drawingID)
	httpReq, err := http.NewRequestWithContext(
		context.Background(),
		"GET",
		url,
		nil,
	)
	if err != nil {
		t.Fatalf("Failed to create get drawing request: %v", err)
	}

	client := &http.Client{Timeout: defaultTimeout}
	resp, err := client.Do(httpReq)
	if err != nil {
		t.Fatalf("Failed to get drawing: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		bodyBytes, _ := io.ReadAll(resp.Body)
		t.Fatalf("Get drawing failed with status %d: %s", resp.StatusCode, string(bodyBytes))
	}

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		t.Fatalf("Failed to decode drawing response: %v", err)
	}

	drawing := result["drawing"].(map[string]interface{})
	return &Drawing{
		DrawingID:         drawing["drawing_id"].(string),
		ProjectID:         drawing["project_id"].(string),
		Name:              drawing["name"].(string),
		Description:       drawing["description"].(string),
		Status:            drawing["status"].(string),
		CurrentRevisionID: drawing["current_revision_id"].(string),
		RevisionCount:     int(drawing["revision_count"].(float64)),
		EntityCount:       int(drawing["entity_count"].(float64)),
		CreatedAt:         drawing["created_at"].(string),
	}
}

// listDrawings lists drawings in a project
func listDrawings(t *testing.T, cfg *SmokeTestConfig, projectID string) []*Drawing {
	url := fmt.Sprintf("%s/api/v1/workspace/projects/%s/drawings?page_size=100", cfg.APIGatewayURL, projectID)
	httpReq, err := http.NewRequestWithContext(
		context.Background(),
		"GET",
		url,
		nil,
	)
	if err != nil {
		t.Fatalf("Failed to create list drawings request: %v", err)
	}

	client := &http.Client{Timeout: defaultTimeout}
	resp, err := client.Do(httpReq)
	if err != nil {
		t.Fatalf("Failed to list drawings: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		bodyBytes, _ := io.ReadAll(resp.Body)
		t.Fatalf("List drawings failed with status %d: %s", resp.StatusCode, string(bodyBytes))
	}

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		t.Fatalf("Failed to decode list response: %v", err)
	}

	drawingsData := result["drawings"].([]interface{})
	var drawings []*Drawing
	for _, d := range drawingsData {
		dMap := d.(map[string]interface{})
		drawings = append(drawings, &Drawing{
			DrawingID:     dMap["drawing_id"].(string),
			ProjectID:     dMap["project_id"].(string),
			Name:          dMap["name"].(string),
			Status:        dMap["status"].(string),
			RevisionCount: int(dMap["revision_count"].(float64)),
			EntityCount:   int(dMap["entity_count"].(float64)),
		})
	}
	return drawings
}

// commitCommand commits a drawing command via API Gateway
func commitCommand(t *testing.T, cfg *SmokeTestConfig, drawingID string, cmd DrawingCommand) map[string]interface{} {
	body, err := json.Marshal(cmd)
	if err != nil {
		t.Fatalf("Failed to marshal command: %v", err)
	}

	url := fmt.Sprintf("%s/api/v1/workspace/drawings/%s/commands", cfg.APIGatewayURL, drawingID)
	httpReq, err := http.NewRequestWithContext(
		context.Background(),
		"POST",
		url,
		bytes.NewReader(body),
	)
	if err != nil {
		t.Fatalf("Failed to create commit command request: %v", err)
	}
	httpReq.Header.Set("Content-Type", "application/json")

	client := &http.Client{Timeout: defaultTimeout}
	resp, err := client.Do(httpReq)
	if err != nil {
		t.Fatalf("Failed to commit command: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		bodyBytes, _ := io.ReadAll(resp.Body)
		t.Fatalf("Commit command failed with status %d: %s", resp.StatusCode, string(bodyBytes))
	}

	var result map[string]interface{}
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		t.Fatalf("Failed to decode commit response: %v", err)
	}

	return result["revision"].(map[string]interface{})
}

