// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TransmissionRoute struct {
	ID                    pgtype.UUID        `json:"id"`
	ProjectID             pgtype.UUID        `json:"project_id"`
	Name                  string             `json:"name"`
	VoltageClass          string             `json:"voltage_class"`
	FarmOutputGeojson     string             `json:"farm_output_geojson"`
	GridInjectionGeojson  string             `json:"grid_injection_geojson"`
	PathGeojson           string             `json:"path_geojson"`
	TowerPositions        []byte             `json:"tower_positions"`
	DistanceM             float64            `json:"distance_m"`
	ConductorCost         float64            `json:"conductor_cost"`
	TowerCost             float64            `json:"tower_cost"`
	RowAcquisitionCost    float64            `json:"row_acquisition_cost"`
	CrossingPremium       float64            `json:"crossing_premium"`
	TotalCost             float64            `json:"total_cost"`
	CostPerKm             float64            `json:"cost_per_km"`
	SegmentExplanations   []byte             `json:"segment_explanations"`
	RouteScore            []byte             `json:"route_score"`
	ApprovalStatus        string             `json:"approval_status"`
	EngineeringReviewedAt pgtype.Timestamptz `json:"engineering_reviewed_at"`
	EngineeringReviewedBy string             `json:"engineering_reviewed_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy            string             `json:"approved_by"`
	GovernanceEvents      []byte             `json:"governance_events"`
	Metadata              []byte             `json:"metadata"`
	RouteSummary          string             `json:"route_summary"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

