// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ApproveTransmissionRoute(ctx context.Context, arg ApproveTransmissionRouteParams) (ApproveTransmissionRouteRow, error)
	CreateTransmissionRoute(ctx context.Context, arg CreateTransmissionRouteParams) (CreateTransmissionRouteRow, error)
	DeleteTransmissionRoute(ctx context.Context, id pgtype.UUID) error
	GetTransmissionRoute(ctx context.Context, id pgtype.UUID) (GetTransmissionRouteRow, error)
	ListTransmissionRoutes(ctx context.Context, projectID pgtype.UUID) ([]ListTransmissionRoutesRow, error)
	SubmitTransmissionRouteForReview(ctx context.Context, arg SubmitTransmissionRouteForReviewParams) (SubmitTransmissionRouteForReviewRow, error)
}

var _ Querier = (*Queries)(nil)

