// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const approveTransmissionRoute = `-- name: ApproveTransmissionRoute :one
UPDATE transmission_routes
SET approval_status = 'approved',
    approved_at = $1,
    approved_by = $2,
    governance_events = $3::jsonb,
    metadata = $4::jsonb,
    route_summary = $5
WHERE id = $6
RETURNING id::text, project_id, name, voltage_class,
    farm_output_geojson, grid_injection_geojson, path_geojson,
    tower_positions::text AS tower_positions_json,
    distance_m, conductor_cost, tower_cost, row_acquisition_cost,
    crossing_premium, total_cost, cost_per_km,
    segment_explanations::text AS segment_explanations_json,
    route_score::text AS route_score_json,
    approval_status, engineering_reviewed_at, engineering_reviewed_by,
    approved_at, approved_by,
    governance_events::text AS governance_events_json,
    metadata::text AS metadata_json,
    route_summary, created_at
`

type ApproveTransmissionRouteParams struct {
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy       string             `json:"approved_by"`
	GovernanceEvents []byte             `json:"governance_events"`
	Metadata         []byte             `json:"metadata"`
	RouteSummary     string             `json:"route_summary"`
	ID               pgtype.UUID        `json:"id"`
}

type ApproveTransmissionRouteRow struct {
	ID                      string             `json:"id"`
	ProjectID               pgtype.UUID        `json:"project_id"`
	Name                    string             `json:"name"`
	VoltageClass            string             `json:"voltage_class"`
	FarmOutputGeojson       string             `json:"farm_output_geojson"`
	GridInjectionGeojson    string             `json:"grid_injection_geojson"`
	PathGeojson             string             `json:"path_geojson"`
	TowerPositionsJson      string             `json:"tower_positions_json"`
	DistanceM               float64            `json:"distance_m"`
	ConductorCost           float64            `json:"conductor_cost"`
	TowerCost               float64            `json:"tower_cost"`
	RowAcquisitionCost      float64            `json:"row_acquisition_cost"`
	CrossingPremium         float64            `json:"crossing_premium"`
	TotalCost               float64            `json:"total_cost"`
	CostPerKm               float64            `json:"cost_per_km"`
	SegmentExplanationsJson string             `json:"segment_explanations_json"`
	RouteScoreJson          string             `json:"route_score_json"`
	ApprovalStatus          string             `json:"approval_status"`
	EngineeringReviewedAt   pgtype.Timestamptz `json:"engineering_reviewed_at"`
	EngineeringReviewedBy   string             `json:"engineering_reviewed_by"`
	ApprovedAt              pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy              string             `json:"approved_by"`
	GovernanceEventsJson    string             `json:"governance_events_json"`
	MetadataJson            string             `json:"metadata_json"`
	RouteSummary            string             `json:"route_summary"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ApproveTransmissionRoute(ctx context.Context, arg ApproveTransmissionRouteParams) (ApproveTransmissionRouteRow, error) {
	row := q.db.QueryRow(ctx, approveTransmissionRoute,
		arg.ApprovedAt,
		arg.ApprovedBy,
		arg.GovernanceEvents,
		arg.Metadata,
		arg.RouteSummary,
		arg.ID,
	)
	var i ApproveTransmissionRouteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.VoltageClass,
		&i.FarmOutputGeojson,
		&i.GridInjectionGeojson,
		&i.PathGeojson,
		&i.TowerPositionsJson,
		&i.DistanceM,
		&i.ConductorCost,
		&i.TowerCost,
		&i.RowAcquisitionCost,
		&i.CrossingPremium,
		&i.TotalCost,
		&i.CostPerKm,
		&i.SegmentExplanationsJson,
		&i.RouteScoreJson,
		&i.ApprovalStatus,
		&i.EngineeringReviewedAt,
		&i.EngineeringReviewedBy,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.GovernanceEventsJson,
		&i.MetadataJson,
		&i.RouteSummary,
		&i.CreatedAt,
	)
	return i, err
}

const createTransmissionRoute = `-- name: CreateTransmissionRoute :one
INSERT INTO transmission_routes (
    id,
    project_id,
    name,
    voltage_class,
    farm_output_geojson,
    grid_injection_geojson,
    path_geojson,
    tower_positions,
    distance_m,
    conductor_cost,
    tower_cost,
    row_acquisition_cost,
    crossing_premium,
    total_cost,
    cost_per_km,
    segment_explanations,
    route_score,
    approval_status,
    engineering_reviewed_at,
    engineering_reviewed_by,
    approved_at,
    approved_by,
    governance_events,
    metadata,
    route_summary
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8::jsonb,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16::jsonb,
    $17::jsonb,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23::jsonb,
    $24::jsonb,
    $25
)
RETURNING id::text, project_id, name, voltage_class,
    farm_output_geojson, grid_injection_geojson, path_geojson,
    tower_positions::text AS tower_positions_json,
    distance_m, conductor_cost, tower_cost, row_acquisition_cost,
    crossing_premium, total_cost, cost_per_km,
    segment_explanations::text AS segment_explanations_json,
    route_score::text AS route_score_json,
    approval_status, engineering_reviewed_at, engineering_reviewed_by,
    approved_at, approved_by,
    governance_events::text AS governance_events_json,
    metadata::text AS metadata_json,
    route_summary, created_at
`

type CreateTransmissionRouteParams struct {
	ID                    pgtype.UUID        `json:"id"`
	ProjectID             pgtype.UUID        `json:"project_id"`
	Name                  string             `json:"name"`
	VoltageClass          string             `json:"voltage_class"`
	FarmOutputGeojson     string             `json:"farm_output_geojson"`
	GridInjectionGeojson  string             `json:"grid_injection_geojson"`
	PathGeojson           string             `json:"path_geojson"`
	TowerPositions        []byte             `json:"tower_positions"`
	DistanceM             float64            `json:"distance_m"`
	ConductorCost         float64            `json:"conductor_cost"`
	TowerCost             float64            `json:"tower_cost"`
	RowAcquisitionCost    float64            `json:"row_acquisition_cost"`
	CrossingPremium       float64            `json:"crossing_premium"`
	TotalCost             float64            `json:"total_cost"`
	CostPerKm             float64            `json:"cost_per_km"`
	SegmentExplanations   []byte             `json:"segment_explanations"`
	RouteScore            []byte             `json:"route_score"`
	ApprovalStatus        string             `json:"approval_status"`
	EngineeringReviewedAt pgtype.Timestamptz `json:"engineering_reviewed_at"`
	EngineeringReviewedBy string             `json:"engineering_reviewed_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy            string             `json:"approved_by"`
	GovernanceEvents      []byte             `json:"governance_events"`
	Metadata              []byte             `json:"metadata"`
	RouteSummary          string             `json:"route_summary"`
}

type CreateTransmissionRouteRow struct {
	ID                      string             `json:"id"`
	ProjectID               pgtype.UUID        `json:"project_id"`
	Name                    string             `json:"name"`
	VoltageClass            string             `json:"voltage_class"`
	FarmOutputGeojson       string             `json:"farm_output_geojson"`
	GridInjectionGeojson    string             `json:"grid_injection_geojson"`
	PathGeojson             string             `json:"path_geojson"`
	TowerPositionsJson      string             `json:"tower_positions_json"`
	DistanceM               float64            `json:"distance_m"`
	ConductorCost           float64            `json:"conductor_cost"`
	TowerCost               float64            `json:"tower_cost"`
	RowAcquisitionCost      float64            `json:"row_acquisition_cost"`
	CrossingPremium         float64            `json:"crossing_premium"`
	TotalCost               float64            `json:"total_cost"`
	CostPerKm               float64            `json:"cost_per_km"`
	SegmentExplanationsJson string             `json:"segment_explanations_json"`
	RouteScoreJson          string             `json:"route_score_json"`
	ApprovalStatus          string             `json:"approval_status"`
	EngineeringReviewedAt   pgtype.Timestamptz `json:"engineering_reviewed_at"`
	EngineeringReviewedBy   string             `json:"engineering_reviewed_by"`
	ApprovedAt              pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy              string             `json:"approved_by"`
	GovernanceEventsJson    string             `json:"governance_events_json"`
	MetadataJson            string             `json:"metadata_json"`
	RouteSummary            string             `json:"route_summary"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTransmissionRoute(ctx context.Context, arg CreateTransmissionRouteParams) (CreateTransmissionRouteRow, error) {
	row := q.db.QueryRow(ctx, createTransmissionRoute,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.VoltageClass,
		arg.FarmOutputGeojson,
		arg.GridInjectionGeojson,
		arg.PathGeojson,
		arg.TowerPositions,
		arg.DistanceM,
		arg.ConductorCost,
		arg.TowerCost,
		arg.RowAcquisitionCost,
		arg.CrossingPremium,
		arg.TotalCost,
		arg.CostPerKm,
		arg.SegmentExplanations,
		arg.RouteScore,
		arg.ApprovalStatus,
		arg.EngineeringReviewedAt,
		arg.EngineeringReviewedBy,
		arg.ApprovedAt,
		arg.ApprovedBy,
		arg.GovernanceEvents,
		arg.Metadata,
		arg.RouteSummary,
	)
	var i CreateTransmissionRouteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.VoltageClass,
		&i.FarmOutputGeojson,
		&i.GridInjectionGeojson,
		&i.PathGeojson,
		&i.TowerPositionsJson,
		&i.DistanceM,
		&i.ConductorCost,
		&i.TowerCost,
		&i.RowAcquisitionCost,
		&i.CrossingPremium,
		&i.TotalCost,
		&i.CostPerKm,
		&i.SegmentExplanationsJson,
		&i.RouteScoreJson,
		&i.ApprovalStatus,
		&i.EngineeringReviewedAt,
		&i.EngineeringReviewedBy,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.GovernanceEventsJson,
		&i.MetadataJson,
		&i.RouteSummary,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTransmissionRoute = `-- name: DeleteTransmissionRoute :exec
DELETE FROM transmission_routes
WHERE id = $1
`

func (q *Queries) DeleteTransmissionRoute(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTransmissionRoute, id)
	return err
}

const getTransmissionRoute = `-- name: GetTransmissionRoute :one
SELECT id::text, project_id, name, voltage_class,
    farm_output_geojson, grid_injection_geojson, path_geojson,
    tower_positions::text AS tower_positions_json,
    distance_m, conductor_cost, tower_cost, row_acquisition_cost,
    crossing_premium, total_cost, cost_per_km,
    segment_explanations::text AS segment_explanations_json,
    route_score::text AS route_score_json,
    approval_status, engineering_reviewed_at, engineering_reviewed_by,
    approved_at, approved_by,
    governance_events::text AS governance_events_json,
    metadata::text AS metadata_json,
    route_summary, created_at
FROM transmission_routes
WHERE id = $1
`

type GetTransmissionRouteRow struct {
	ID                      string             `json:"id"`
	ProjectID               pgtype.UUID        `json:"project_id"`
	Name                    string             `json:"name"`
	VoltageClass            string             `json:"voltage_class"`
	FarmOutputGeojson       string             `json:"farm_output_geojson"`
	GridInjectionGeojson    string             `json:"grid_injection_geojson"`
	PathGeojson             string             `json:"path_geojson"`
	TowerPositionsJson      string             `json:"tower_positions_json"`
	DistanceM               float64            `json:"distance_m"`
	ConductorCost           float64            `json:"conductor_cost"`
	TowerCost               float64            `json:"tower_cost"`
	RowAcquisitionCost      float64            `json:"row_acquisition_cost"`
	CrossingPremium         float64            `json:"crossing_premium"`
	TotalCost               float64            `json:"total_cost"`
	CostPerKm               float64            `json:"cost_per_km"`
	SegmentExplanationsJson string             `json:"segment_explanations_json"`
	RouteScoreJson          string             `json:"route_score_json"`
	ApprovalStatus          string             `json:"approval_status"`
	EngineeringReviewedAt   pgtype.Timestamptz `json:"engineering_reviewed_at"`
	EngineeringReviewedBy   string             `json:"engineering_reviewed_by"`
	ApprovedAt              pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy              string             `json:"approved_by"`
	GovernanceEventsJson    string             `json:"governance_events_json"`
	MetadataJson            string             `json:"metadata_json"`
	RouteSummary            string             `json:"route_summary"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetTransmissionRoute(ctx context.Context, id pgtype.UUID) (GetTransmissionRouteRow, error) {
	row := q.db.QueryRow(ctx, getTransmissionRoute, id)
	var i GetTransmissionRouteRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.VoltageClass,
		&i.FarmOutputGeojson,
		&i.GridInjectionGeojson,
		&i.PathGeojson,
		&i.TowerPositionsJson,
		&i.DistanceM,
		&i.ConductorCost,
		&i.TowerCost,
		&i.RowAcquisitionCost,
		&i.CrossingPremium,
		&i.TotalCost,
		&i.CostPerKm,
		&i.SegmentExplanationsJson,
		&i.RouteScoreJson,
		&i.ApprovalStatus,
		&i.EngineeringReviewedAt,
		&i.EngineeringReviewedBy,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.GovernanceEventsJson,
		&i.MetadataJson,
		&i.RouteSummary,
		&i.CreatedAt,
	)
	return i, err
}

const listTransmissionRoutes = `-- name: ListTransmissionRoutes :many
SELECT id::text, project_id, name, voltage_class,
    farm_output_geojson, grid_injection_geojson, path_geojson,
    tower_positions::text AS tower_positions_json,
    distance_m, conductor_cost, tower_cost, row_acquisition_cost,
    crossing_premium, total_cost, cost_per_km,
    segment_explanations::text AS segment_explanations_json,
    route_score::text AS route_score_json,
    approval_status, engineering_reviewed_at, engineering_reviewed_by,
    approved_at, approved_by,
    governance_events::text AS governance_events_json,
    metadata::text AS metadata_json,
    route_summary, created_at
FROM transmission_routes
WHERE project_id = $1
ORDER BY created_at DESC
`

type ListTransmissionRoutesRow struct {
	ID                      string             `json:"id"`
	ProjectID               pgtype.UUID        `json:"project_id"`
	Name                    string             `json:"name"`
	VoltageClass            string             `json:"voltage_class"`
	FarmOutputGeojson       string             `json:"farm_output_geojson"`
	GridInjectionGeojson    string             `json:"grid_injection_geojson"`
	PathGeojson             string             `json:"path_geojson"`
	TowerPositionsJson      string             `json:"tower_positions_json"`
	DistanceM               float64            `json:"distance_m"`
	ConductorCost           float64            `json:"conductor_cost"`
	TowerCost               float64            `json:"tower_cost"`
	RowAcquisitionCost      float64            `json:"row_acquisition_cost"`
	CrossingPremium         float64            `json:"crossing_premium"`
	TotalCost               float64            `json:"total_cost"`
	CostPerKm               float64            `json:"cost_per_km"`
	SegmentExplanationsJson string             `json:"segment_explanations_json"`
	RouteScoreJson          string             `json:"route_score_json"`
	ApprovalStatus          string             `json:"approval_status"`
	EngineeringReviewedAt   pgtype.Timestamptz `json:"engineering_reviewed_at"`
	EngineeringReviewedBy   string             `json:"engineering_reviewed_by"`
	ApprovedAt              pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy              string             `json:"approved_by"`
	GovernanceEventsJson    string             `json:"governance_events_json"`
	MetadataJson            string             `json:"metadata_json"`
	RouteSummary            string             `json:"route_summary"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTransmissionRoutes(ctx context.Context, projectID pgtype.UUID) ([]ListTransmissionRoutesRow, error) {
	rows, err := q.db.Query(ctx, listTransmissionRoutes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransmissionRoutesRow
	for rows.Next() {
		var i ListTransmissionRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.VoltageClass,
			&i.FarmOutputGeojson,
			&i.GridInjectionGeojson,
			&i.PathGeojson,
			&i.TowerPositionsJson,
			&i.DistanceM,
			&i.ConductorCost,
			&i.TowerCost,
			&i.RowAcquisitionCost,
			&i.CrossingPremium,
			&i.TotalCost,
			&i.CostPerKm,
			&i.SegmentExplanationsJson,
			&i.RouteScoreJson,
			&i.ApprovalStatus,
			&i.EngineeringReviewedAt,
			&i.EngineeringReviewedBy,
			&i.ApprovedAt,
			&i.ApprovedBy,
			&i.GovernanceEventsJson,
			&i.MetadataJson,
			&i.RouteSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitTransmissionRouteForReview = `-- name: SubmitTransmissionRouteForReview :one
UPDATE transmission_routes
SET approval_status = 'engineering_review',
    engineering_reviewed_at = $1,
    engineering_reviewed_by = $2,
    governance_events = $3::jsonb,
    metadata = $4::jsonb,
    route_summary = $5
WHERE id = $6
RETURNING id::text, project_id, name, voltage_class,
    farm_output_geojson, grid_injection_geojson, path_geojson,
    tower_positions::text AS tower_positions_json,
    distance_m, conductor_cost, tower_cost, row_acquisition_cost,
    crossing_premium, total_cost, cost_per_km,
    segment_explanations::text AS segment_explanations_json,
    route_score::text AS route_score_json,
    approval_status, engineering_reviewed_at, engineering_reviewed_by,
    approved_at, approved_by,
    governance_events::text AS governance_events_json,
    metadata::text AS metadata_json,
    route_summary, created_at
`

type SubmitTransmissionRouteForReviewParams struct {
	EngineeringReviewedAt pgtype.Timestamptz `json:"engineering_reviewed_at"`
	EngineeringReviewedBy string             `json:"engineering_reviewed_by"`
	GovernanceEvents      []byte             `json:"governance_events"`
	Metadata              []byte             `json:"metadata"`
	RouteSummary          string             `json:"route_summary"`
	ID                    pgtype.UUID        `json:"id"`
}

type SubmitTransmissionRouteForReviewRow struct {
	ID                      string             `json:"id"`
	ProjectID               pgtype.UUID        `json:"project_id"`
	Name                    string             `json:"name"`
	VoltageClass            string             `json:"voltage_class"`
	FarmOutputGeojson       string             `json:"farm_output_geojson"`
	GridInjectionGeojson    string             `json:"grid_injection_geojson"`
	PathGeojson             string             `json:"path_geojson"`
	TowerPositionsJson      string             `json:"tower_positions_json"`
	DistanceM               float64            `json:"distance_m"`
	ConductorCost           float64            `json:"conductor_cost"`
	TowerCost               float64            `json:"tower_cost"`
	RowAcquisitionCost      float64            `json:"row_acquisition_cost"`
	CrossingPremium         float64            `json:"crossing_premium"`
	TotalCost               float64            `json:"total_cost"`
	CostPerKm               float64            `json:"cost_per_km"`
	SegmentExplanationsJson string             `json:"segment_explanations_json"`
	RouteScoreJson          string             `json:"route_score_json"`
	ApprovalStatus          string             `json:"approval_status"`
	EngineeringReviewedAt   pgtype.Timestamptz `json:"engineering_reviewed_at"`
	EngineeringReviewedBy   string             `json:"engineering_reviewed_by"`
	ApprovedAt              pgtype.Timestamptz `json:"approved_at"`
	ApprovedBy              string             `json:"approved_by"`
	GovernanceEventsJson    string             `json:"governance_events_json"`
	MetadataJson            string             `json:"metadata_json"`
	RouteSummary            string             `json:"route_summary"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SubmitTransmissionRouteForReview(ctx context.Context, arg SubmitTransmissionRouteForReviewParams) (SubmitTransmissionRouteForReviewRow, error) {
	row := q.db.QueryRow(ctx, submitTransmissionRouteForReview,
		arg.EngineeringReviewedAt,
		arg.EngineeringReviewedBy,
		arg.GovernanceEvents,
		arg.Metadata,
		arg.RouteSummary,
		arg.ID,
	)
	var i SubmitTransmissionRouteForReviewRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.VoltageClass,
		&i.FarmOutputGeojson,
		&i.GridInjectionGeojson,
		&i.PathGeojson,
		&i.TowerPositionsJson,
		&i.DistanceM,
		&i.ConductorCost,
		&i.TowerCost,
		&i.RowAcquisitionCost,
		&i.CrossingPremium,
		&i.TotalCost,
		&i.CostPerKm,
		&i.SegmentExplanationsJson,
		&i.RouteScoreJson,
		&i.ApprovalStatus,
		&i.EngineeringReviewedAt,
		&i.EngineeringReviewedBy,
		&i.ApprovedAt,
		&i.ApprovedBy,
		&i.GovernanceEventsJson,
		&i.MetadataJson,
		&i.RouteSummary,
		&i.CreatedAt,
	)
	return i, err
}

