[package]
name = "geo-compute"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "geo_http_bridge"
path = "src/bin/http_bridge.rs"

[dependencies]
common = { path = "../common" }
rayon = "1.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tiny_http = "0.12"
bridge-core = { path = "../bridge-core" }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "geo_bench"
harness = false
