// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrchestrationDeadLetter struct {
	ID          int64              `json:"id"`
	JobID       pgtype.UUID        `json:"job_id"`
	Reason      string             `json:"reason"`
	PayloadJson []byte             `json:"payload_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OrchestrationIdempotencyKey struct {
	ID             int64              `json:"id"`
	ProjectID      string             `json:"project_id"`
	IdempotencyKey string             `json:"idempotency_key"`
	JobID          pgtype.UUID        `json:"job_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type OrchestrationJob struct {
	ID           pgtype.UUID        `json:"id"`
	ProjectID    string             `json:"project_id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	Priority     int32              `json:"priority"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	PayloadJson  []byte             `json:"payload_json"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

type OrchestrationJobArtifact struct {
	ID        int64              `json:"id"`
	JobID     pgtype.UUID        `json:"job_id"`
	Kind      string             `json:"kind"`
	Uri       string             `json:"uri"`
	Checksum  *string            `json:"checksum"`
	SizeBytes int64              `json:"size_bytes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrchestrationJobAttempt struct {
	ID           int64              `json:"id"`
	JobID        pgtype.UUID        `json:"job_id"`
	AttemptNo    int32              `json:"attempt_no"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

