// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateJob(ctx context.Context, arg CreateJobParams) error
	DeleteArtifactsByJobID(ctx context.Context, dollar_1 pgtype.UUID) error
	GetArtifactsByJobID(ctx context.Context, dollar_1 pgtype.UUID) ([]GetArtifactsByJobIDRow, error)
	GetDeadLetter(ctx context.Context, dollar_1 pgtype.UUID) (GetDeadLetterRow, error)
	GetIdempotencyJobID(ctx context.Context, arg GetIdempotencyJobIDParams) (string, error)
	GetJob(ctx context.Context, dollar_1 pgtype.UUID) (GetJobRow, error)
	InsertArtifact(ctx context.Context, arg InsertArtifactParams) error
	InsertDeadLetter(ctx context.Context, arg InsertDeadLetterParams) error
	InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error
	ListDeadLetters(ctx context.Context, arg ListDeadLettersParams) ([]ListDeadLettersRow, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error)
	MarkRetryPending(ctx context.Context, arg MarkRetryPendingParams) error
	UpdateJob(ctx context.Context, arg UpdateJobParams) error
	UpsertAttempt(ctx context.Context, arg UpsertAttemptParams) error
}

var _ Querier = (*Queries)(nil)

