// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO orchestration_jobs (
    id, project_id, job_type, status, priority, attempts, max_attempts,
    payload_json, error_message, created_at, started_at, completed_at, next_retry_at
) VALUES (
    $1::uuid, $2, $3, $4, $5, $6, $7,
    $8::jsonb, $9, $10, $11, $12, $13
)
`

type CreateJobParams struct {
	Column1      pgtype.UUID        `json:"column_1"`
	ProjectID    string             `json:"project_id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	Priority     int32              `json:"priority"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	Column8      []byte             `json:"column_8"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.Exec(ctx, createJob,
		arg.Column1,
		arg.ProjectID,
		arg.JobType,
		arg.Status,
		arg.Priority,
		arg.Attempts,
		arg.MaxAttempts,
		arg.Column8,
		arg.ErrorMessage,
		arg.CreatedAt,
		arg.StartedAt,
		arg.CompletedAt,
		arg.NextRetryAt,
	)
	return err
}

const deleteArtifactsByJobID = `-- name: DeleteArtifactsByJobID :exec
DELETE FROM orchestration_job_artifacts WHERE job_id = $1::uuid
`

func (q *Queries) DeleteArtifactsByJobID(ctx context.Context, dollar_1 pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteArtifactsByJobID, dollar_1)
	return err
}

const getArtifactsByJobID = `-- name: GetArtifactsByJobID :many
SELECT kind, uri, checksum, size_bytes
FROM orchestration_job_artifacts
WHERE job_id = $1::uuid
ORDER BY id ASC
`

type GetArtifactsByJobIDRow struct {
	Kind      string  `json:"kind"`
	Uri       string  `json:"uri"`
	Checksum  *string `json:"checksum"`
	SizeBytes int64   `json:"size_bytes"`
}

func (q *Queries) GetArtifactsByJobID(ctx context.Context, dollar_1 pgtype.UUID) ([]GetArtifactsByJobIDRow, error) {
	rows, err := q.db.Query(ctx, getArtifactsByJobID, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtifactsByJobIDRow
	for rows.Next() {
		var i GetArtifactsByJobIDRow
		if err := rows.Scan(
			&i.Kind,
			&i.Uri,
			&i.Checksum,
			&i.SizeBytes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeadLetter = `-- name: GetDeadLetter :one
SELECT id::text, job_id::text, reason, payload_json::text, created_at
FROM orchestration_dead_letters
WHERE job_id = $1::uuid
`

type GetDeadLetterRow struct {
	ID          string             `json:"id"`
	JobID       string             `json:"job_id"`
	Reason      string             `json:"reason"`
	PayloadJson string             `json:"payload_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDeadLetter(ctx context.Context, dollar_1 pgtype.UUID) (GetDeadLetterRow, error) {
	row := q.db.QueryRow(ctx, getDeadLetter, dollar_1)
	var i GetDeadLetterRow
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Reason,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const getIdempotencyJobID = `-- name: GetIdempotencyJobID :one
SELECT job_id::text
FROM orchestration_idempotency_keys
WHERE project_id = $1
    AND idempotency_key = $2
`

type GetIdempotencyJobIDParams struct {
	ProjectID      string `json:"project_id"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetIdempotencyJobID(ctx context.Context, arg GetIdempotencyJobIDParams) (string, error) {
	row := q.db.QueryRow(ctx, getIdempotencyJobID, arg.ProjectID, arg.IdempotencyKey)
	var job_id string
	err := row.Scan(&job_id)
	return job_id, err
}

const getJob = `-- name: GetJob :one
SELECT id::text, project_id, job_type, status, priority, attempts, max_attempts,
       payload_json::text, error_message, created_at, started_at, completed_at, next_retry_at
FROM orchestration_jobs
WHERE id = $1::uuid
`

type GetJobRow struct {
	ID           string             `json:"id"`
	ProjectID    string             `json:"project_id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	Priority     int32              `json:"priority"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	PayloadJson  string             `json:"payload_json"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) GetJob(ctx context.Context, dollar_1 pgtype.UUID) (GetJobRow, error) {
	row := q.db.QueryRow(ctx, getJob, dollar_1)
	var i GetJobRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.JobType,
		&i.Status,
		&i.Priority,
		&i.Attempts,
		&i.MaxAttempts,
		&i.PayloadJson,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.NextRetryAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :exec
INSERT INTO orchestration_job_artifacts (job_id, kind, uri, checksum, size_bytes)
VALUES ($1::uuid, $2, $3, $4, $5)
`

type InsertArtifactParams struct {
	Column1   pgtype.UUID `json:"column_1"`
	Kind      string      `json:"kind"`
	Uri       string      `json:"uri"`
	Checksum  *string     `json:"checksum"`
	SizeBytes int64       `json:"size_bytes"`
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) error {
	_, err := q.db.Exec(ctx, insertArtifact,
		arg.Column1,
		arg.Kind,
		arg.Uri,
		arg.Checksum,
		arg.SizeBytes,
	)
	return err
}

const insertDeadLetter = `-- name: InsertDeadLetter :exec
INSERT INTO orchestration_dead_letters (job_id, reason, payload_json)
VALUES ($1::uuid, $2, $3::jsonb)
`

type InsertDeadLetterParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Reason  string      `json:"reason"`
	Column3 []byte      `json:"column_3"`
}

func (q *Queries) InsertDeadLetter(ctx context.Context, arg InsertDeadLetterParams) error {
	_, err := q.db.Exec(ctx, insertDeadLetter, arg.Column1, arg.Reason, arg.Column3)
	return err
}

const insertIdempotencyKey = `-- name: InsertIdempotencyKey :exec
INSERT INTO orchestration_idempotency_keys (project_id, idempotency_key, job_id)
VALUES ($1, $2, $3::uuid)
ON CONFLICT (project_id, idempotency_key) DO NOTHING
`

type InsertIdempotencyKeyParams struct {
	ProjectID      string      `json:"project_id"`
	IdempotencyKey string      `json:"idempotency_key"`
	Column3        pgtype.UUID `json:"column_3"`
}

func (q *Queries) InsertIdempotencyKey(ctx context.Context, arg InsertIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyKey, arg.ProjectID, arg.IdempotencyKey, arg.Column3)
	return err
}

const listDeadLetters = `-- name: ListDeadLetters :many
SELECT id::text, job_id::text, reason, payload_json::text, created_at
FROM orchestration_dead_letters
WHERE job_id::text IN (
    SELECT j.id::text
    FROM orchestration_jobs j
    WHERE j.project_id = $1
)
ORDER BY created_at DESC
LIMIT $2
`

type ListDeadLettersParams struct {
	ProjectID string `json:"project_id"`
	Limit     int32  `json:"limit"`
}

type ListDeadLettersRow struct {
	ID          string             `json:"id"`
	JobID       string             `json:"job_id"`
	Reason      string             `json:"reason"`
	PayloadJson string             `json:"payload_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDeadLetters(ctx context.Context, arg ListDeadLettersParams) ([]ListDeadLettersRow, error) {
	rows, err := q.db.Query(ctx, listDeadLetters, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeadLettersRow
	for rows.Next() {
		var i ListDeadLettersRow
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Reason,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id::text, project_id, job_type, status, priority, attempts, max_attempts,
       payload_json::text, error_message, created_at, started_at, completed_at, next_retry_at
FROM orchestration_jobs
WHERE ($1::text = '' OR project_id = $1)
  AND ($2::text = '' OR status = $2)
ORDER BY priority DESC, created_at ASC
LIMIT $3
`

type ListJobsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
}

type ListJobsRow struct {
	ID           string             `json:"id"`
	ProjectID    string             `json:"project_id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	Priority     int32              `json:"priority"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	PayloadJson  string             `json:"payload_json"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]ListJobsRow, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListJobsRow
	for rows.Next() {
		var i ListJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.JobType,
			&i.Status,
			&i.Priority,
			&i.Attempts,
			&i.MaxAttempts,
			&i.PayloadJson,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.NextRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRetryPending = `-- name: MarkRetryPending :exec
UPDATE orchestration_jobs
SET status = $2,
    error_message = $3,
    next_retry_at = $4,
    completed_at = NULL
WHERE id = $1::uuid
`

type MarkRetryPendingParams struct {
	Column1      pgtype.UUID        `json:"column_1"`
	Status       string             `json:"status"`
	ErrorMessage *string            `json:"error_message"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) MarkRetryPending(ctx context.Context, arg MarkRetryPendingParams) error {
	_, err := q.db.Exec(ctx, markRetryPending,
		arg.Column1,
		arg.Status,
		arg.ErrorMessage,
		arg.NextRetryAt,
	)
	return err
}

const updateJob = `-- name: UpdateJob :exec
UPDATE orchestration_jobs
SET project_id = $2,
    job_type = $3,
    status = $4,
    priority = $5,
    attempts = $6,
    max_attempts = $7,
    payload_json = $8::jsonb,
    error_message = $9,
    started_at = $10,
    completed_at = $11,
    next_retry_at = $12
WHERE id = $1::uuid
`

type UpdateJobParams struct {
	Column1      pgtype.UUID        `json:"column_1"`
	ProjectID    string             `json:"project_id"`
	JobType      string             `json:"job_type"`
	Status       string             `json:"status"`
	Priority     int32              `json:"priority"`
	Attempts     int32              `json:"attempts"`
	MaxAttempts  int32              `json:"max_attempts"`
	Column8      []byte             `json:"column_8"`
	ErrorMessage *string            `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	NextRetryAt  pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) UpdateJob(ctx context.Context, arg UpdateJobParams) error {
	_, err := q.db.Exec(ctx, updateJob,
		arg.Column1,
		arg.ProjectID,
		arg.JobType,
		arg.Status,
		arg.Priority,
		arg.Attempts,
		arg.MaxAttempts,
		arg.Column8,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
		arg.NextRetryAt,
	)
	return err
}

const upsertAttempt = `-- name: UpsertAttempt :exec
INSERT INTO orchestration_job_attempts (
    job_id, attempt_no, status, started_at, finished_at, error_message
) VALUES ($1::uuid, $2, $3, $4, $5, $6)
ON CONFLICT (job_id, attempt_no)
DO UPDATE SET status = EXCLUDED.status,
              started_at = EXCLUDED.started_at,
              finished_at = EXCLUDED.finished_at,
              error_message = EXCLUDED.error_message
`

type UpsertAttemptParams struct {
	Column1      pgtype.UUID        `json:"column_1"`
	AttemptNo    int32              `json:"attempt_no"`
	Status       string             `json:"status"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	ErrorMessage *string            `json:"error_message"`
}

func (q *Queries) UpsertAttempt(ctx context.Context, arg UpsertAttemptParams) error {
	_, err := q.db.Exec(ctx, upsertAttempt,
		arg.Column1,
		arg.AttemptNo,
		arg.Status,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ErrorMessage,
	)
	return err
}

