// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AssetCategory string

const (
	AssetCategoryPanel       AssetCategory = "panel"
	AssetCategoryInverter    AssetCategory = "inverter"
	AssetCategoryTransformer AssetCategory = "transformer"
	AssetCategoryTracker     AssetCategory = "tracker"
	AssetCategoryCombiner    AssetCategory = "combiner"
	AssetCategoryFuse        AssetCategory = "fuse"
	AssetCategoryCable       AssetCategory = "cable"
	AssetCategoryMounting    AssetCategory = "mounting"
	AssetCategoryMeter       AssetCategory = "meter"
	AssetCategoryOther       AssetCategory = "other"
)

func (e *AssetCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetCategory(s)
	case string:
		*e = AssetCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetCategory: %T", src)
	}
	return nil
}

type NullAssetCategory struct {
	AssetCategory AssetCategory `json:"asset_category"`
	Valid         bool          `json:"valid"` // Valid is true if AssetCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetCategory) Scan(value interface{}) error {
	if value == nil {
		ns.AssetCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetCategory), nil
}

type Asset struct {
	ID               pgtype.UUID   `json:"id"`
	Name             string        `json:"name"`
	Manufacturer     string        `json:"manufacturer"`
	Model            string        `json:"model"`
	Category         AssetCategory `json:"category"`
	Dimensions       []byte        `json:"dimensions"`
	ElectricalParams []byte        `json:"electrical_params"`
	Model3dPath      string        `json:"model_3d_path"`
	DatasheetPath    string        `json:"datasheet_path"`
	Metadata         []byte        `json:"metadata"`
}
