// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (id, name, manufacturer, model, category, dimensions, electrical_params, model_3d_path, datasheet_path, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, manufacturer, model, category, dimensions, electrical_params, model_3d_path, datasheet_path, metadata
`

type CreateAssetParams struct {
	ID               pgtype.UUID   `json:"id"`
	Name             string        `json:"name"`
	Manufacturer     string        `json:"manufacturer"`
	Model            string        `json:"model"`
	Category         AssetCategory `json:"category"`
	Dimensions       []byte        `json:"dimensions"`
	ElectricalParams []byte        `json:"electrical_params"`
	Model3dPath      string        `json:"model_3d_path"`
	DatasheetPath    string        `json:"datasheet_path"`
	Metadata         []byte        `json:"metadata"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.ID,
		arg.Name,
		arg.Manufacturer,
		arg.Model,
		arg.Category,
		arg.Dimensions,
		arg.ElectricalParams,
		arg.Model3dPath,
		arg.DatasheetPath,
		arg.Metadata,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Manufacturer,
		&i.Model,
		&i.Category,
		&i.Dimensions,
		&i.ElectricalParams,
		&i.Model3dPath,
		&i.DatasheetPath,
		&i.Metadata,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, name, manufacturer, model, category, dimensions, electrical_params, model_3d_path, datasheet_path, metadata FROM assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Manufacturer,
		&i.Model,
		&i.Category,
		&i.Dimensions,
		&i.ElectricalParams,
		&i.Model3dPath,
		&i.DatasheetPath,
		&i.Metadata,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT id, name, manufacturer, model, category, dimensions, electrical_params, model_3d_path, datasheet_path, metadata FROM assets ORDER BY category, name
`

func (q *Queries) ListAssets(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Manufacturer,
			&i.Model,
			&i.Category,
			&i.Dimensions,
			&i.ElectricalParams,
			&i.Model3dPath,
			&i.DatasheetPath,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetsByCategory = `-- name: ListAssetsByCategory :many
SELECT id, name, manufacturer, model, category, dimensions, electrical_params, model_3d_path, datasheet_path, metadata FROM assets WHERE category = $1 ORDER BY name
`

func (q *Queries) ListAssetsByCategory(ctx context.Context, category AssetCategory) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Manufacturer,
			&i.Model,
			&i.Category,
			&i.Dimensions,
			&i.ElectricalParams,
			&i.Model3dPath,
			&i.DatasheetPath,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAssets = `-- name: SearchAssets :many
SELECT id, name, manufacturer, model, category, dimensions, electrical_params, model_3d_path, datasheet_path, metadata FROM assets
WHERE ($1::asset_category IS NULL OR category = $1)
  AND ($2::text IS NULL OR manufacturer ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR name ILIKE '%' || $3 || '%' OR model ILIKE '%' || $3 || '%')
ORDER BY category, name
`

type SearchAssetsParams struct {
	Column1 AssetCategory `json:"column_1"`
	Column2 string        `json:"column_2"`
	Column3 string        `json:"column_3"`
}

func (q *Queries) SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchAssets, arg.Column1, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Manufacturer,
			&i.Model,
			&i.Category,
			&i.Dimensions,
			&i.ElectricalParams,
			&i.Model3dPath,
			&i.DatasheetPath,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsset = `-- name: UpdateAsset :exec
UPDATE assets
SET name = $2, manufacturer = $3, model = $4, category = $5,
    dimensions = $6, electrical_params = $7, model_3d_path = $8,
    datasheet_path = $9, metadata = $10
WHERE id = $1
`

type UpdateAssetParams struct {
	ID               pgtype.UUID   `json:"id"`
	Name             string        `json:"name"`
	Manufacturer     string        `json:"manufacturer"`
	Model            string        `json:"model"`
	Category         AssetCategory `json:"category"`
	Dimensions       []byte        `json:"dimensions"`
	ElectricalParams []byte        `json:"electrical_params"`
	Model3dPath      string        `json:"model_3d_path"`
	DatasheetPath    string        `json:"datasheet_path"`
	Metadata         []byte        `json:"metadata"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) error {
	_, err := q.db.Exec(ctx, updateAsset,
		arg.ID,
		arg.Name,
		arg.Manufacturer,
		arg.Model,
		arg.Category,
		arg.Dimensions,
		arg.ElectricalParams,
		arg.Model3dPath,
		arg.DatasheetPath,
		arg.Metadata,
	)
	return err
}
