// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	DeleteAsset(ctx context.Context, id pgtype.UUID) error
	GetAssetByID(ctx context.Context, id pgtype.UUID) (Asset, error)
	ListAssets(ctx context.Context) ([]Asset, error)
	ListAssetsByCategory(ctx context.Context, category AssetCategory) ([]Asset, error)
	SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]Asset, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) error
}

var _ Querier = (*Queries)(nil)
