// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MlActiveModel struct {
	ID              string             `json:"id"`
	TaskType        string             `json:"task_type"`
	CurrentModelID  string             `json:"current_model_id"`
	PreviousModelID *string            `json:"previous_model_id"`
	PromotedAt      pgtype.Timestamptz `json:"promoted_at"`
	DeploymentID    *string            `json:"deployment_id"`
}

type MlAuditEvent struct {
	ID           pgtype.UUID        `json:"id"`
	EventType    string             `json:"event_type"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Actor        *string            `json:"actor"`
	ActorIp      *string            `json:"actor_ip"`
	Changes      []byte             `json:"changes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MlDataset struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	TaskType   string             `json:"task_type"`
	SourceType string             `json:"source_type"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Metadata   []byte             `json:"metadata"`
}

type MlDeployment struct {
	ID                  string             `json:"id"`
	ModelVersionID      string             `json:"model_version_id"`
	Status              string             `json:"status"`
	DeployedBy          string             `json:"deployed_by"`
	ApprovalID          *string            `json:"approval_id"`
	Policy              []byte             `json:"policy"`
	TrafficPercent      *int16             `json:"traffic_percent"`
	CanaryStartedAt     pgtype.Timestamptz `json:"canary_started_at"`
	PromotedToActiveAt  pgtype.Timestamptz `json:"promoted_to_active_at"`
	DeployedAt          pgtype.Timestamptz `json:"deployed_at"`
	RolledBackAt        pgtype.Timestamptz `json:"rolled_back_at"`
	RollbackReason      *string            `json:"rollback_reason"`
	RollbackTriggeredBy *string            `json:"rollback_triggered_by"`
	Notes               *string            `json:"notes"`
}

type MlEvalRun struct {
	ID               string             `json:"id"`
	CandidateModelID string             `json:"candidate_model_id"`
	ChampionModelID  *string            `json:"champion_model_id"`
	Status           string             `json:"status"`
	DatasetSplit     string             `json:"dataset_split"`
	Metrics          []byte             `json:"metrics"`
	CandidateWins    *bool              `json:"candidate_wins"`
	Recommendation   *string            `json:"recommendation"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type MlFeatureDriftStat struct {
	ID             int64              `json:"id"`
	ModelVersionID string             `json:"model_version_id"`
	FeatureName    string             `json:"feature_name"`
	DriftDetector  string             `json:"drift_detector"`
	DriftScore     *float64           `json:"drift_score"`
	PValue         *float64           `json:"p_value"`
	DriftDetected  *bool              `json:"drift_detected"`
	WindowStart    pgtype.Timestamptz `json:"window_start"`
	WindowEnd      pgtype.Timestamptz `json:"window_end"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MlFeatureSchema struct {
	ID                  string             `json:"id"`
	TaskType            string             `json:"task_type"`
	Version             int32              `json:"version"`
	FeatureNames        []string           `json:"feature_names"`
	FeatureDtypes       []string           `json:"feature_dtypes"`
	NormalizationParams []byte             `json:"normalization_params"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type MlFeedbackLabel struct {
	ID              pgtype.UUID        `json:"id"`
	PredictionLogID pgtype.UUID        `json:"prediction_log_id"`
	ActualLabel     float64            `json:"actual_label"`
	LabelType       string             `json:"label_type"`
	SubmittedBy     *string            `json:"submitted_by"`
	Notes           *string            `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type MlModelVersion struct {
	ID                string             `json:"id"`
	TaskType          string             `json:"task_type"`
	TrainingRunID     string             `json:"training_run_id"`
	Status            string             `json:"status"`
	ArtifactPath      string             `json:"artifact_path"`
	ArtifactHash      string             `json:"artifact_hash"`
	FeatureSchemaHash string             `json:"feature_schema_hash"`
	Metrics           []byte             `json:"metrics"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
}

type MlMonitoringMetric struct {
	ID             int64              `json:"id"`
	ModelVersionID string             `json:"model_version_id"`
	MetricType     string             `json:"metric_type"`
	MetricValue    float64            `json:"metric_value"`
	WindowStart    pgtype.Timestamptz `json:"window_start"`
	WindowEnd      pgtype.Timestamptz `json:"window_end"`
	DriftDetected  *bool              `json:"drift_detected"`
	AlertSent      *bool              `json:"alert_sent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type MlPredictionLog struct {
	ID                pgtype.UUID        `json:"id"`
	PredictionID      string             `json:"prediction_id"`
	SiteID            pgtype.UUID        `json:"site_id"`
	TaskType          string             `json:"task_type"`
	ModelVersionID    string             `json:"model_version_id"`
	InputFeatures     []byte             `json:"input_features"`
	PredictedValue    *float64           `json:"predicted_value"`
	PredictedLower    *float64           `json:"predicted_lower"`
	PredictedUpper    *float64           `json:"predicted_upper"`
	Confidence        *float64           `json:"confidence"`
	FeatureSchemaHash string             `json:"feature_schema_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MlTrainingRun struct {
	ID           string             `json:"id"`
	TaskType     string             `json:"task_type"`
	Status       string             `json:"status"`
	DatasetID    pgtype.UUID        `json:"dataset_id"`
	Config       []byte             `json:"config"`
	Hyperparams  []byte             `json:"hyperparams"`
	Metrics      []byte             `json:"metrics"`
	ErrorMessage *string            `json:"error_message"`
	TriggeredBy  *string            `json:"triggered_by"`
	CommitHash   *string            `json:"commit_hash"`
	ArtifactPath *string            `json:"artifact_path"`
	ArtifactHash *string            `json:"artifact_hash"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type MlTrainingSample struct {
	ID         int64              `json:"id"`
	DatasetID  pgtype.UUID        `json:"dataset_id"`
	SiteID     pgtype.UUID        `json:"site_id"`
	Features   []byte             `json:"features"`
	Label      float64            `json:"label"`
	SplitSet   string             `json:"split_set"`
	SampleDate pgtype.Timestamptz `json:"sample_date"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

