// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveOldModels = `-- name: ArchiveOldModels :many
DELETE FROM ml_model_versions
WHERE task_type = $1
  AND status = 'archived'
  AND created_at < NOW() - INTERVAL '1 day' * $2
RETURNING ml_model_versions.id
`

type ArchiveOldModelsParams struct {
	TaskType string      `json:"task_type"`
	Column2  interface{} `json:"column_2"`
}

func (q *Queries) ArchiveOldModels(ctx context.Context, arg ArchiveOldModelsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, archiveOldModels, arg.TaskType, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDatasetSamples = `-- name: CountDatasetSamples :one
SELECT COUNT(*) as count
FROM ml_training_samples
WHERE dataset_id = $1
`

func (q *Queries) CountDatasetSamples(ctx context.Context, datasetID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDatasetSamples, datasetID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDeployment = `-- name: CreateDeployment :exec

INSERT INTO ml_deployments (
    id, model_version_id, status, deployed_by, approval_id, policy, traffic_percent
) VALUES (
    $1, $2, $3, $4, $5, $6::jsonb, $7
)
`

type CreateDeploymentParams struct {
	ID             string  `json:"id"`
	ModelVersionID string  `json:"model_version_id"`
	Status         string  `json:"status"`
	DeployedBy     string  `json:"deployed_by"`
	ApprovalID     *string `json:"approval_id"`
	Column6        []byte  `json:"column_6"`
	TrafficPercent *int16  `json:"traffic_percent"`
}

// ============================================================
// Deployments
// ============================================================
func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error {
	_, err := q.db.Exec(ctx, createDeployment,
		arg.ID,
		arg.ModelVersionID,
		arg.Status,
		arg.DeployedBy,
		arg.ApprovalID,
		arg.Column6,
		arg.TrafficPercent,
	)
	return err
}

const createEvalRun = `-- name: CreateEvalRun :exec

INSERT INTO ml_eval_runs (
    id, candidate_model_id, champion_model_id, status, dataset_split
) VALUES (
    $1, $2, $3, $4, $5
)
`

type CreateEvalRunParams struct {
	ID               string  `json:"id"`
	CandidateModelID string  `json:"candidate_model_id"`
	ChampionModelID  *string `json:"champion_model_id"`
	Status           string  `json:"status"`
	DatasetSplit     string  `json:"dataset_split"`
}

// ============================================================
// Evaluation
// ============================================================
func (q *Queries) CreateEvalRun(ctx context.Context, arg CreateEvalRunParams) error {
	_, err := q.db.Exec(ctx, createEvalRun,
		arg.ID,
		arg.CandidateModelID,
		arg.ChampionModelID,
		arg.Status,
		arg.DatasetSplit,
	)
	return err
}

const createFeatureSchema = `-- name: CreateFeatureSchema :exec
INSERT INTO ml_feature_schemas (
    id, task_type, version, feature_names, feature_dtypes, normalization_params
) VALUES (
    $1, $2, $3, $4, $5, $6::jsonb
)
`

type CreateFeatureSchemaParams struct {
	ID            string   `json:"id"`
	TaskType      string   `json:"task_type"`
	Version       int32    `json:"version"`
	FeatureNames  []string `json:"feature_names"`
	FeatureDtypes []string `json:"feature_dtypes"`
	Column6       []byte   `json:"column_6"`
}

func (q *Queries) CreateFeatureSchema(ctx context.Context, arg CreateFeatureSchemaParams) error {
	_, err := q.db.Exec(ctx, createFeatureSchema,
		arg.ID,
		arg.TaskType,
		arg.Version,
		arg.FeatureNames,
		arg.FeatureDtypes,
		arg.Column6,
	)
	return err
}

const createModelVersion = `-- name: CreateModelVersion :exec

INSERT INTO ml_model_versions (
    id, task_type, training_run_id, status, artifact_path, artifact_hash,
    feature_schema_hash, metrics, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8::jsonb, $9::jsonb
)
`

type CreateModelVersionParams struct {
	ID                string `json:"id"`
	TaskType          string `json:"task_type"`
	TrainingRunID     string `json:"training_run_id"`
	Status            string `json:"status"`
	ArtifactPath      string `json:"artifact_path"`
	ArtifactHash      string `json:"artifact_hash"`
	FeatureSchemaHash string `json:"feature_schema_hash"`
	Column8           []byte `json:"column_8"`
	Column9           []byte `json:"column_9"`
}

// ============================================================
// Model Versions
// ============================================================
func (q *Queries) CreateModelVersion(ctx context.Context, arg CreateModelVersionParams) error {
	_, err := q.db.Exec(ctx, createModelVersion,
		arg.ID,
		arg.TaskType,
		arg.TrainingRunID,
		arg.Status,
		arg.ArtifactPath,
		arg.ArtifactHash,
		arg.FeatureSchemaHash,
		arg.Column8,
		arg.Column9,
	)
	return err
}

const createTrainingRun = `-- name: CreateTrainingRun :exec

INSERT INTO ml_training_runs (
    id, task_type, status, dataset_id, config, hyperparams,
    triggered_by, commit_hash, artifact_path, artifact_hash
) VALUES (
    $1, $2, $3, $4::uuid, $5::jsonb, $6::jsonb,
    $7, $8, $9, $10
)
`

type CreateTrainingRunParams struct {
	ID           string      `json:"id"`
	TaskType     string      `json:"task_type"`
	Status       string      `json:"status"`
	Column4      pgtype.UUID `json:"column_4"`
	Column5      []byte      `json:"column_5"`
	Column6      []byte      `json:"column_6"`
	TriggeredBy  *string     `json:"triggered_by"`
	CommitHash   *string     `json:"commit_hash"`
	ArtifactPath *string     `json:"artifact_path"`
	ArtifactHash *string     `json:"artifact_hash"`
}

// ============================================================
// Training Runs
// ============================================================
func (q *Queries) CreateTrainingRun(ctx context.Context, arg CreateTrainingRunParams) error {
	_, err := q.db.Exec(ctx, createTrainingRun,
		arg.ID,
		arg.TaskType,
		arg.Status,
		arg.Column4,
		arg.Column5,
		arg.Column6,
		arg.TriggeredBy,
		arg.CommitHash,
		arg.ArtifactPath,
		arg.ArtifactHash,
	)
	return err
}

const getActiveModel = `-- name: GetActiveModel :one

SELECT id, task_type, current_model_id, previous_model_id, promoted_at, deployment_id
FROM ml_active_models
WHERE task_type = $1
`

// ============================================================
// Active Models
// ============================================================
func (q *Queries) GetActiveModel(ctx context.Context, taskType string) (MlActiveModel, error) {
	row := q.db.QueryRow(ctx, getActiveModel, taskType)
	var i MlActiveModel
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.CurrentModelID,
		&i.PreviousModelID,
		&i.PromotedAt,
		&i.DeploymentID,
	)
	return i, err
}

const getAuditEvents = `-- name: GetAuditEvents :many
SELECT id::text, event_type, resource_type, resource_id, actor, actor_ip,
       changes::text, created_at
FROM ml_audit_events
WHERE resource_type = $1 AND resource_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type GetAuditEventsParams struct {
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	Limit        int32  `json:"limit"`
}

type GetAuditEventsRow struct {
	ID           string             `json:"id"`
	EventType    string             `json:"event_type"`
	ResourceType string             `json:"resource_type"`
	ResourceID   string             `json:"resource_id"`
	Actor        *string            `json:"actor"`
	ActorIp      *string            `json:"actor_ip"`
	Changes      string             `json:"changes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAuditEvents(ctx context.Context, arg GetAuditEventsParams) ([]GetAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, getAuditEvents, arg.ResourceType, arg.ResourceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditEventsRow
	for rows.Next() {
		var i GetAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.ResourceType,
			&i.ResourceID,
			&i.Actor,
			&i.ActorIp,
			&i.Changes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChampionModel = `-- name: GetChampionModel :one
SELECT m.id, m.task_type, m.training_run_id, m.status, m.artifact_path, 
       m.artifact_hash, m.feature_schema_hash, m.metrics::text, 
       m.metadata::text, m.created_at, m.archived_at
FROM ml_model_versions m
INNER JOIN ml_active_models a ON m.id = a.current_model_id
WHERE a.task_type = $1
`

type GetChampionModelRow struct {
	ID                string             `json:"id"`
	TaskType          string             `json:"task_type"`
	TrainingRunID     string             `json:"training_run_id"`
	Status            string             `json:"status"`
	ArtifactPath      string             `json:"artifact_path"`
	ArtifactHash      string             `json:"artifact_hash"`
	FeatureSchemaHash string             `json:"feature_schema_hash"`
	MMetrics          string             `json:"m_metrics"`
	MMetadata         string             `json:"m_metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) GetChampionModel(ctx context.Context, taskType string) (GetChampionModelRow, error) {
	row := q.db.QueryRow(ctx, getChampionModel, taskType)
	var i GetChampionModelRow
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.TrainingRunID,
		&i.Status,
		&i.ArtifactPath,
		&i.ArtifactHash,
		&i.FeatureSchemaHash,
		&i.MMetrics,
		&i.MMetadata,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, model_version_id, status, deployed_by, approval_id, policy::text,
       traffic_percent, canary_started_at, promoted_to_active_at, deployed_at,
       rolled_back_at, rollback_reason, rollback_triggered_by, notes
FROM ml_deployments
WHERE id = $1
`

type GetDeploymentRow struct {
	ID                  string             `json:"id"`
	ModelVersionID      string             `json:"model_version_id"`
	Status              string             `json:"status"`
	DeployedBy          string             `json:"deployed_by"`
	ApprovalID          *string            `json:"approval_id"`
	Policy              string             `json:"policy"`
	TrafficPercent      *int16             `json:"traffic_percent"`
	CanaryStartedAt     pgtype.Timestamptz `json:"canary_started_at"`
	PromotedToActiveAt  pgtype.Timestamptz `json:"promoted_to_active_at"`
	DeployedAt          pgtype.Timestamptz `json:"deployed_at"`
	RolledBackAt        pgtype.Timestamptz `json:"rolled_back_at"`
	RollbackReason      *string            `json:"rollback_reason"`
	RollbackTriggeredBy *string            `json:"rollback_triggered_by"`
	Notes               *string            `json:"notes"`
}

func (q *Queries) GetDeployment(ctx context.Context, id string) (GetDeploymentRow, error) {
	row := q.db.QueryRow(ctx, getDeployment, id)
	var i GetDeploymentRow
	err := row.Scan(
		&i.ID,
		&i.ModelVersionID,
		&i.Status,
		&i.DeployedBy,
		&i.ApprovalID,
		&i.Policy,
		&i.TrafficPercent,
		&i.CanaryStartedAt,
		&i.PromotedToActiveAt,
		&i.DeployedAt,
		&i.RolledBackAt,
		&i.RollbackReason,
		&i.RollbackTriggeredBy,
		&i.Notes,
	)
	return i, err
}

const getEvalRun = `-- name: GetEvalRun :one
SELECT id, candidate_model_id, champion_model_id, status, dataset_split,
       metrics::text, candidate_wins, recommendation, completed_at, created_at
FROM ml_eval_runs
WHERE id = $1
`

type GetEvalRunRow struct {
	ID               string             `json:"id"`
	CandidateModelID string             `json:"candidate_model_id"`
	ChampionModelID  *string            `json:"champion_model_id"`
	Status           string             `json:"status"`
	DatasetSplit     string             `json:"dataset_split"`
	Metrics          string             `json:"metrics"`
	CandidateWins    *bool              `json:"candidate_wins"`
	Recommendation   *string            `json:"recommendation"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetEvalRun(ctx context.Context, id string) (GetEvalRunRow, error) {
	row := q.db.QueryRow(ctx, getEvalRun, id)
	var i GetEvalRunRow
	err := row.Scan(
		&i.ID,
		&i.CandidateModelID,
		&i.ChampionModelID,
		&i.Status,
		&i.DatasetSplit,
		&i.Metrics,
		&i.CandidateWins,
		&i.Recommendation,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getFeatureDriftStats = `-- name: GetFeatureDriftStats :many
SELECT id, model_version_id, feature_name, drift_detector, drift_score,
       p_value, drift_detected, window_start, window_end, created_at
FROM ml_feature_drift_stats
WHERE model_version_id = $1
  AND window_start > NOW() - INTERVAL '1 day' * $2
ORDER BY window_end DESC
`

type GetFeatureDriftStatsParams struct {
	ModelVersionID string      `json:"model_version_id"`
	Column2        interface{} `json:"column_2"`
}

func (q *Queries) GetFeatureDriftStats(ctx context.Context, arg GetFeatureDriftStatsParams) ([]MlFeatureDriftStat, error) {
	rows, err := q.db.Query(ctx, getFeatureDriftStats, arg.ModelVersionID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MlFeatureDriftStat
	for rows.Next() {
		var i MlFeatureDriftStat
		if err := rows.Scan(
			&i.ID,
			&i.ModelVersionID,
			&i.FeatureName,
			&i.DriftDetector,
			&i.DriftScore,
			&i.PValue,
			&i.DriftDetected,
			&i.WindowStart,
			&i.WindowEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeatureSchema = `-- name: GetFeatureSchema :one

SELECT id, task_type, version, feature_names, feature_dtypes, 
       normalization_params::text, created_at
FROM ml_feature_schemas
WHERE id = $1
`

type GetFeatureSchemaRow struct {
	ID                  string             `json:"id"`
	TaskType            string             `json:"task_type"`
	Version             int32              `json:"version"`
	FeatureNames        []string           `json:"feature_names"`
	FeatureDtypes       []string           `json:"feature_dtypes"`
	NormalizationParams string             `json:"normalization_params"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

// ============================================================
// Feature Schemas
// ============================================================
func (q *Queries) GetFeatureSchema(ctx context.Context, id string) (GetFeatureSchemaRow, error) {
	row := q.db.QueryRow(ctx, getFeatureSchema, id)
	var i GetFeatureSchemaRow
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Version,
		&i.FeatureNames,
		&i.FeatureDtypes,
		&i.NormalizationParams,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestCandidateModel = `-- name: GetLatestCandidateModel :one
SELECT id, task_type, training_run_id, status, artifact_path, artifact_hash,
       feature_schema_hash, metrics::text, metadata::text, created_at, archived_at
FROM ml_model_versions
WHERE task_type = $1 AND status = 'candidate'
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestCandidateModelRow struct {
	ID                string             `json:"id"`
	TaskType          string             `json:"task_type"`
	TrainingRunID     string             `json:"training_run_id"`
	Status            string             `json:"status"`
	ArtifactPath      string             `json:"artifact_path"`
	ArtifactHash      string             `json:"artifact_hash"`
	FeatureSchemaHash string             `json:"feature_schema_hash"`
	Metrics           string             `json:"metrics"`
	Metadata          string             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) GetLatestCandidateModel(ctx context.Context, taskType string) (GetLatestCandidateModelRow, error) {
	row := q.db.QueryRow(ctx, getLatestCandidateModel, taskType)
	var i GetLatestCandidateModelRow
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.TrainingRunID,
		&i.Status,
		&i.ArtifactPath,
		&i.ArtifactHash,
		&i.FeatureSchemaHash,
		&i.Metrics,
		&i.Metadata,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getModelVersion = `-- name: GetModelVersion :one
SELECT id, task_type, training_run_id, status, artifact_path, artifact_hash,
       feature_schema_hash, metrics::text, metadata::text, created_at, archived_at
FROM ml_model_versions
WHERE id = $1
`

type GetModelVersionRow struct {
	ID                string             `json:"id"`
	TaskType          string             `json:"task_type"`
	TrainingRunID     string             `json:"training_run_id"`
	Status            string             `json:"status"`
	ArtifactPath      string             `json:"artifact_path"`
	ArtifactHash      string             `json:"artifact_hash"`
	FeatureSchemaHash string             `json:"feature_schema_hash"`
	Metrics           string             `json:"metrics"`
	Metadata          string             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) GetModelVersion(ctx context.Context, id string) (GetModelVersionRow, error) {
	row := q.db.QueryRow(ctx, getModelVersion, id)
	var i GetModelVersionRow
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.TrainingRunID,
		&i.Status,
		&i.ArtifactPath,
		&i.ArtifactHash,
		&i.FeatureSchemaHash,
		&i.Metrics,
		&i.Metadata,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getPredictionLog = `-- name: GetPredictionLog :one
SELECT id::text, prediction_id, site_id::text, task_type, model_version_id,
       input_features::text, predicted_value, predicted_lower, predicted_upper,
       confidence, feature_schema_hash, created_at
FROM ml_prediction_logs
WHERE prediction_id = $1
`

type GetPredictionLogRow struct {
	ID                string             `json:"id"`
	PredictionID      string             `json:"prediction_id"`
	SiteID            string             `json:"site_id"`
	TaskType          string             `json:"task_type"`
	ModelVersionID    string             `json:"model_version_id"`
	InputFeatures     string             `json:"input_features"`
	PredictedValue    *float64           `json:"predicted_value"`
	PredictedLower    *float64           `json:"predicted_lower"`
	PredictedUpper    *float64           `json:"predicted_upper"`
	Confidence        *float64           `json:"confidence"`
	FeatureSchemaHash string             `json:"feature_schema_hash"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetPredictionLog(ctx context.Context, predictionID string) (GetPredictionLogRow, error) {
	row := q.db.QueryRow(ctx, getPredictionLog, predictionID)
	var i GetPredictionLogRow
	err := row.Scan(
		&i.ID,
		&i.PredictionID,
		&i.SiteID,
		&i.TaskType,
		&i.ModelVersionID,
		&i.InputFeatures,
		&i.PredictedValue,
		&i.PredictedLower,
		&i.PredictedUpper,
		&i.Confidence,
		&i.FeatureSchemaHash,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentMonitoringMetrics = `-- name: GetRecentMonitoringMetrics :many
SELECT id, model_version_id, metric_type, metric_value, window_start, window_end,
       drift_detected, alert_sent, created_at
FROM ml_monitoring_metrics
WHERE model_version_id = $1
  AND metric_type = $2
  AND window_end > NOW() - INTERVAL '1 hour' * $3
ORDER BY window_end DESC
LIMIT 1000
`

type GetRecentMonitoringMetricsParams struct {
	ModelVersionID string      `json:"model_version_id"`
	MetricType     string      `json:"metric_type"`
	Column3        interface{} `json:"column_3"`
}

func (q *Queries) GetRecentMonitoringMetrics(ctx context.Context, arg GetRecentMonitoringMetricsParams) ([]MlMonitoringMetric, error) {
	rows, err := q.db.Query(ctx, getRecentMonitoringMetrics, arg.ModelVersionID, arg.MetricType, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MlMonitoringMetric
	for rows.Next() {
		var i MlMonitoringMetric
		if err := rows.Scan(
			&i.ID,
			&i.ModelVersionID,
			&i.MetricType,
			&i.MetricValue,
			&i.WindowStart,
			&i.WindowEnd,
			&i.DriftDetected,
			&i.AlertSent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainingDataset = `-- name: GetTrainingDataset :many

SELECT features::text, label
FROM ml_training_samples
WHERE dataset_id = (
    SELECT ml_training_runs.dataset_id FROM ml_training_runs WHERE ml_training_runs.id = $1
)
AND split_set = $2
ORDER BY created_at
`

type GetTrainingDatasetParams struct {
	ID       string `json:"id"`
	SplitSet string `json:"split_set"`
}

type GetTrainingDatasetRow struct {
	Features string  `json:"features"`
	Label    float64 `json:"label"`
}

// ============================================================
// Helper Queries
// ============================================================
func (q *Queries) GetTrainingDataset(ctx context.Context, arg GetTrainingDatasetParams) ([]GetTrainingDatasetRow, error) {
	rows, err := q.db.Query(ctx, getTrainingDataset, arg.ID, arg.SplitSet)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrainingDatasetRow
	for rows.Next() {
		var i GetTrainingDatasetRow
		if err := rows.Scan(&i.Features, &i.Label); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrainingRun = `-- name: GetTrainingRun :one
SELECT id, task_type, status, dataset_id::text, config::text, hyperparams::text,
       metrics::text, error_message, triggered_by, commit_hash,
       artifact_path, artifact_hash, started_at, completed_at, created_at
FROM ml_training_runs
WHERE id = $1
`

type GetTrainingRunRow struct {
	ID           string             `json:"id"`
	TaskType     string             `json:"task_type"`
	Status       string             `json:"status"`
	DatasetID    string             `json:"dataset_id"`
	Config       string             `json:"config"`
	Hyperparams  string             `json:"hyperparams"`
	Metrics      string             `json:"metrics"`
	ErrorMessage *string            `json:"error_message"`
	TriggeredBy  *string            `json:"triggered_by"`
	CommitHash   *string            `json:"commit_hash"`
	ArtifactPath *string            `json:"artifact_path"`
	ArtifactHash *string            `json:"artifact_hash"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetTrainingRun(ctx context.Context, id string) (GetTrainingRunRow, error) {
	row := q.db.QueryRow(ctx, getTrainingRun, id)
	var i GetTrainingRunRow
	err := row.Scan(
		&i.ID,
		&i.TaskType,
		&i.Status,
		&i.DatasetID,
		&i.Config,
		&i.Hyperparams,
		&i.Metrics,
		&i.ErrorMessage,
		&i.TriggeredBy,
		&i.CommitHash,
		&i.ArtifactPath,
		&i.ArtifactHash,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listModelVersions = `-- name: ListModelVersions :many
SELECT id, task_type, training_run_id, status, artifact_path, artifact_hash,
       feature_schema_hash, metrics::text, metadata::text, created_at, archived_at
FROM ml_model_versions
WHERE task_type = $1
  AND ($2::text = '' OR status = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListModelVersionsParams struct {
	TaskType string `json:"task_type"`
	Column2  string `json:"column_2"`
	Limit    int32  `json:"limit"`
}

type ListModelVersionsRow struct {
	ID                string             `json:"id"`
	TaskType          string             `json:"task_type"`
	TrainingRunID     string             `json:"training_run_id"`
	Status            string             `json:"status"`
	ArtifactPath      string             `json:"artifact_path"`
	ArtifactHash      string             `json:"artifact_hash"`
	FeatureSchemaHash string             `json:"feature_schema_hash"`
	Metrics           string             `json:"metrics"`
	Metadata          string             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) ListModelVersions(ctx context.Context, arg ListModelVersionsParams) ([]ListModelVersionsRow, error) {
	rows, err := q.db.Query(ctx, listModelVersions, arg.TaskType, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelVersionsRow
	for rows.Next() {
		var i ListModelVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.TrainingRunID,
			&i.Status,
			&i.ArtifactPath,
			&i.ArtifactHash,
			&i.FeatureSchemaHash,
			&i.Metrics,
			&i.Metadata,
			&i.CreatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingRuns = `-- name: ListTrainingRuns :many
SELECT id, task_type, status, dataset_id::text, config::text, hyperparams::text,
       metrics::text, error_message, triggered_by, commit_hash,
       artifact_path, artifact_hash, started_at, completed_at, created_at
FROM ml_training_runs
WHERE task_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTrainingRunsParams struct {
	TaskType string `json:"task_type"`
	Limit    int32  `json:"limit"`
}

type ListTrainingRunsRow struct {
	ID           string             `json:"id"`
	TaskType     string             `json:"task_type"`
	Status       string             `json:"status"`
	DatasetID    string             `json:"dataset_id"`
	Config       string             `json:"config"`
	Hyperparams  string             `json:"hyperparams"`
	Metrics      string             `json:"metrics"`
	ErrorMessage *string            `json:"error_message"`
	TriggeredBy  *string            `json:"triggered_by"`
	CommitHash   *string            `json:"commit_hash"`
	ArtifactPath *string            `json:"artifact_path"`
	ArtifactHash *string            `json:"artifact_hash"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTrainingRuns(ctx context.Context, arg ListTrainingRunsParams) ([]ListTrainingRunsRow, error) {
	rows, err := q.db.Query(ctx, listTrainingRuns, arg.TaskType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrainingRunsRow
	for rows.Next() {
		var i ListTrainingRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskType,
			&i.Status,
			&i.DatasetID,
			&i.Config,
			&i.Hyperparams,
			&i.Metrics,
			&i.ErrorMessage,
			&i.TriggeredBy,
			&i.CommitHash,
			&i.ArtifactPath,
			&i.ArtifactHash,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logPrediction = `-- name: LogPrediction :exec

INSERT INTO ml_prediction_logs (
    prediction_id, site_id, task_type, model_version_id, 
    input_features, predicted_value, predicted_lower, predicted_upper, 
    confidence, feature_schema_hash
) VALUES (
    $1, $2, $3, $4, 
    $5::jsonb, $6, $7, $8, 
    $9, $10
)
`

type LogPredictionParams struct {
	PredictionID      string      `json:"prediction_id"`
	SiteID            pgtype.UUID `json:"site_id"`
	TaskType          string      `json:"task_type"`
	ModelVersionID    string      `json:"model_version_id"`
	Column5           []byte      `json:"column_5"`
	PredictedValue    *float64    `json:"predicted_value"`
	PredictedLower    *float64    `json:"predicted_lower"`
	PredictedUpper    *float64    `json:"predicted_upper"`
	Confidence        *float64    `json:"confidence"`
	FeatureSchemaHash string      `json:"feature_schema_hash"`
}

// Prediction Logs & Feedback
func (q *Queries) LogPrediction(ctx context.Context, arg LogPredictionParams) error {
	_, err := q.db.Exec(ctx, logPrediction,
		arg.PredictionID,
		arg.SiteID,
		arg.TaskType,
		arg.ModelVersionID,
		arg.Column5,
		arg.PredictedValue,
		arg.PredictedLower,
		arg.PredictedUpper,
		arg.Confidence,
		arg.FeatureSchemaHash,
	)
	return err
}

const recordAuditEvent = `-- name: RecordAuditEvent :exec

INSERT INTO ml_audit_events (
    event_type, resource_type, resource_id, actor, actor_ip, changes
) VALUES (
    $1, $2, $3, $4, $5, $6::jsonb
)
`

type RecordAuditEventParams struct {
	EventType    string  `json:"event_type"`
	ResourceType string  `json:"resource_type"`
	ResourceID   string  `json:"resource_id"`
	Actor        *string `json:"actor"`
	ActorIp      *string `json:"actor_ip"`
	Column6      []byte  `json:"column_6"`
}

// ============================================================
// Audit Trail
// ============================================================
func (q *Queries) RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) error {
	_, err := q.db.Exec(ctx, recordAuditEvent,
		arg.EventType,
		arg.ResourceType,
		arg.ResourceID,
		arg.Actor,
		arg.ActorIp,
		arg.Column6,
	)
	return err
}

const recordFeatureDrift = `-- name: RecordFeatureDrift :exec

INSERT INTO ml_feature_drift_stats (
    model_version_id, feature_name, drift_detector, drift_score, p_value,
    drift_detected, window_start, window_end
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
`

type RecordFeatureDriftParams struct {
	ModelVersionID string             `json:"model_version_id"`
	FeatureName    string             `json:"feature_name"`
	DriftDetector  string             `json:"drift_detector"`
	DriftScore     *float64           `json:"drift_score"`
	PValue         *float64           `json:"p_value"`
	DriftDetected  *bool              `json:"drift_detected"`
	WindowStart    pgtype.Timestamptz `json:"window_start"`
	WindowEnd      pgtype.Timestamptz `json:"window_end"`
}

// ============================================================
// Drift Detection
// ============================================================
func (q *Queries) RecordFeatureDrift(ctx context.Context, arg RecordFeatureDriftParams) error {
	_, err := q.db.Exec(ctx, recordFeatureDrift,
		arg.ModelVersionID,
		arg.FeatureName,
		arg.DriftDetector,
		arg.DriftScore,
		arg.PValue,
		arg.DriftDetected,
		arg.WindowStart,
		arg.WindowEnd,
	)
	return err
}

const recordMonitoringMetric = `-- name: RecordMonitoringMetric :exec

INSERT INTO ml_monitoring_metrics (
    model_version_id, metric_type, metric_value, window_start, window_end, drift_detected
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type RecordMonitoringMetricParams struct {
	ModelVersionID string             `json:"model_version_id"`
	MetricType     string             `json:"metric_type"`
	MetricValue    float64            `json:"metric_value"`
	WindowStart    pgtype.Timestamptz `json:"window_start"`
	WindowEnd      pgtype.Timestamptz `json:"window_end"`
	DriftDetected  *bool              `json:"drift_detected"`
}

// ============================================================
// Monitoring
// ============================================================
func (q *Queries) RecordMonitoringMetric(ctx context.Context, arg RecordMonitoringMetricParams) error {
	_, err := q.db.Exec(ctx, recordMonitoringMetric,
		arg.ModelVersionID,
		arg.MetricType,
		arg.MetricValue,
		arg.WindowStart,
		arg.WindowEnd,
		arg.DriftDetected,
	)
	return err
}

const rollbackDeployment = `-- name: RollbackDeployment :exec
UPDATE ml_deployments
SET status = 'rolled_back', rolled_back_at = NOW(),
    rollback_reason = $2, rollback_triggered_by = $3
WHERE id = $1
`

type RollbackDeploymentParams struct {
	ID                  string  `json:"id"`
	RollbackReason      *string `json:"rollback_reason"`
	RollbackTriggeredBy *string `json:"rollback_triggered_by"`
}

func (q *Queries) RollbackDeployment(ctx context.Context, arg RollbackDeploymentParams) error {
	_, err := q.db.Exec(ctx, rollbackDeployment, arg.ID, arg.RollbackReason, arg.RollbackTriggeredBy)
	return err
}

const setActiveModel = `-- name: SetActiveModel :exec
INSERT INTO ml_active_models (id, task_type, current_model_id, previous_model_id, deployment_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (task_type) DO UPDATE SET
    current_model_id = EXCLUDED.current_model_id,
    previous_model_id = EXCLUDED.previous_model_id,
    promoted_at = NOW(),
    deployment_id = EXCLUDED.deployment_id
`

type SetActiveModelParams struct {
	ID              string  `json:"id"`
	TaskType        string  `json:"task_type"`
	CurrentModelID  string  `json:"current_model_id"`
	PreviousModelID *string `json:"previous_model_id"`
	DeploymentID    *string `json:"deployment_id"`
}

func (q *Queries) SetActiveModel(ctx context.Context, arg SetActiveModelParams) error {
	_, err := q.db.Exec(ctx, setActiveModel,
		arg.ID,
		arg.TaskType,
		arg.CurrentModelID,
		arg.PreviousModelID,
		arg.DeploymentID,
	)
	return err
}

const submitFeedback = `-- name: SubmitFeedback :one
INSERT INTO ml_feedback_labels (
    prediction_log_id, actual_label, label_type, submitted_by, notes
) VALUES (
    $1::uuid, $2, $3, $4, $5
)
RETURNING id::text
`

type SubmitFeedbackParams struct {
	Column1     pgtype.UUID `json:"column_1"`
	ActualLabel float64     `json:"actual_label"`
	LabelType   string      `json:"label_type"`
	SubmittedBy *string     `json:"submitted_by"`
	Notes       *string     `json:"notes"`
}

func (q *Queries) SubmitFeedback(ctx context.Context, arg SubmitFeedbackParams) (string, error) {
	row := q.db.QueryRow(ctx, submitFeedback,
		arg.Column1,
		arg.ActualLabel,
		arg.LabelType,
		arg.SubmittedBy,
		arg.Notes,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateDeploymentCanary = `-- name: UpdateDeploymentCanary :exec
UPDATE ml_deployments
SET status = $2, canary_started_at = $3, traffic_percent = $4
WHERE id = $1
`

type UpdateDeploymentCanaryParams struct {
	ID              string             `json:"id"`
	Status          string             `json:"status"`
	CanaryStartedAt pgtype.Timestamptz `json:"canary_started_at"`
	TrafficPercent  *int16             `json:"traffic_percent"`
}

func (q *Queries) UpdateDeploymentCanary(ctx context.Context, arg UpdateDeploymentCanaryParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentCanary,
		arg.ID,
		arg.Status,
		arg.CanaryStartedAt,
		arg.TrafficPercent,
	)
	return err
}

const updateDeploymentStatus = `-- name: UpdateDeploymentStatus :exec
UPDATE ml_deployments
SET status = $2,
    promoted_to_active_at = CASE WHEN $2 = 'active' THEN NOW() ELSE promoted_to_active_at END
WHERE id = $1
`

type UpdateDeploymentStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeploymentStatus, arg.ID, arg.Status)
	return err
}

const updateEvalRunResults = `-- name: UpdateEvalRunResults :exec
UPDATE ml_eval_runs
SET status = $2, metrics = $3::jsonb, candidate_wins = $4,
    recommendation = $5, completed_at = NOW()
WHERE id = $1
`

type UpdateEvalRunResultsParams struct {
	ID             string  `json:"id"`
	Status         string  `json:"status"`
	Column3        []byte  `json:"column_3"`
	CandidateWins  *bool   `json:"candidate_wins"`
	Recommendation *string `json:"recommendation"`
}

func (q *Queries) UpdateEvalRunResults(ctx context.Context, arg UpdateEvalRunResultsParams) error {
	_, err := q.db.Exec(ctx, updateEvalRunResults,
		arg.ID,
		arg.Status,
		arg.Column3,
		arg.CandidateWins,
		arg.Recommendation,
	)
	return err
}

const updateModelVersionStatus = `-- name: UpdateModelVersionStatus :exec
UPDATE ml_model_versions
SET status = $2, archived_at = CASE WHEN $2 = 'archived' THEN NOW() ELSE archived_at END
WHERE id = $1
`

type UpdateModelVersionStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateModelVersionStatus(ctx context.Context, arg UpdateModelVersionStatusParams) error {
	_, err := q.db.Exec(ctx, updateModelVersionStatus, arg.ID, arg.Status)
	return err
}

const updateTrainingRunCompleted = `-- name: UpdateTrainingRunCompleted :exec
UPDATE ml_training_runs
SET status = $2, metrics = $3::jsonb, artifact_path = $4, artifact_hash = $5,
    completed_at = NOW()
WHERE id = $1
`

type UpdateTrainingRunCompletedParams struct {
	ID           string  `json:"id"`
	Status       string  `json:"status"`
	Column3      []byte  `json:"column_3"`
	ArtifactPath *string `json:"artifact_path"`
	ArtifactHash *string `json:"artifact_hash"`
}

func (q *Queries) UpdateTrainingRunCompleted(ctx context.Context, arg UpdateTrainingRunCompletedParams) error {
	_, err := q.db.Exec(ctx, updateTrainingRunCompleted,
		arg.ID,
		arg.Status,
		arg.Column3,
		arg.ArtifactPath,
		arg.ArtifactHash,
	)
	return err
}

const updateTrainingRunMetrics = `-- name: UpdateTrainingRunMetrics :exec
UPDATE ml_training_runs
SET metrics = $2::jsonb, status = $3,
    started_at = COALESCE(started_at, NOW()),
    completed_at = CASE WHEN $3 = 'completed' THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateTrainingRunMetricsParams struct {
	ID      string `json:"id"`
	Column2 []byte `json:"column_2"`
	Status  string `json:"status"`
}

func (q *Queries) UpdateTrainingRunMetrics(ctx context.Context, arg UpdateTrainingRunMetricsParams) error {
	_, err := q.db.Exec(ctx, updateTrainingRunMetrics, arg.ID, arg.Column2, arg.Status)
	return err
}

const updateTrainingRunStatus = `-- name: UpdateTrainingRunStatus :exec
UPDATE ml_training_runs
SET status = $2, error_message = $3
WHERE id = $1
`

type UpdateTrainingRunStatusParams struct {
	ID           string  `json:"id"`
	Status       string  `json:"status"`
	ErrorMessage *string `json:"error_message"`
}

func (q *Queries) UpdateTrainingRunStatus(ctx context.Context, arg UpdateTrainingRunStatusParams) error {
	_, err := q.db.Exec(ctx, updateTrainingRunStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}

