// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ArchiveOldModels(ctx context.Context, arg ArchiveOldModelsParams) ([]string, error)
	CountDatasetSamples(ctx context.Context, datasetID pgtype.UUID) (int64, error)
	// ============================================================
	// Deployments
	// ============================================================
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) error
	// ============================================================
	// Evaluation
	// ============================================================
	CreateEvalRun(ctx context.Context, arg CreateEvalRunParams) error
	CreateFeatureSchema(ctx context.Context, arg CreateFeatureSchemaParams) error
	// ============================================================
	// Model Versions
	// ============================================================
	CreateModelVersion(ctx context.Context, arg CreateModelVersionParams) error
	// ============================================================
	// Training Runs
	// ============================================================
	CreateTrainingRun(ctx context.Context, arg CreateTrainingRunParams) error
	// ============================================================
	// Active Models
	// ============================================================
	GetActiveModel(ctx context.Context, taskType string) (MlActiveModel, error)
	GetAuditEvents(ctx context.Context, arg GetAuditEventsParams) ([]GetAuditEventsRow, error)
	GetChampionModel(ctx context.Context, taskType string) (GetChampionModelRow, error)
	GetDeployment(ctx context.Context, id string) (GetDeploymentRow, error)
	GetEvalRun(ctx context.Context, id string) (GetEvalRunRow, error)
	GetFeatureDriftStats(ctx context.Context, arg GetFeatureDriftStatsParams) ([]MlFeatureDriftStat, error)
	// ============================================================
	// Feature Schemas
	// ============================================================
	GetFeatureSchema(ctx context.Context, id string) (GetFeatureSchemaRow, error)
	GetLatestCandidateModel(ctx context.Context, taskType string) (GetLatestCandidateModelRow, error)
	GetModelVersion(ctx context.Context, id string) (GetModelVersionRow, error)
	GetPredictionLog(ctx context.Context, predictionID string) (GetPredictionLogRow, error)
	GetRecentMonitoringMetrics(ctx context.Context, arg GetRecentMonitoringMetricsParams) ([]MlMonitoringMetric, error)
	// ============================================================
	// Helper Queries
	// ============================================================
	GetTrainingDataset(ctx context.Context, arg GetTrainingDatasetParams) ([]GetTrainingDatasetRow, error)
	GetTrainingRun(ctx context.Context, id string) (GetTrainingRunRow, error)
	ListModelVersions(ctx context.Context, arg ListModelVersionsParams) ([]ListModelVersionsRow, error)
	ListTrainingRuns(ctx context.Context, arg ListTrainingRunsParams) ([]ListTrainingRunsRow, error)
	// Prediction Logs & Feedback
	LogPrediction(ctx context.Context, arg LogPredictionParams) error
	// ============================================================
	// Audit Trail
	// ============================================================
	RecordAuditEvent(ctx context.Context, arg RecordAuditEventParams) error
	// ============================================================
	// Drift Detection
	// ============================================================
	RecordFeatureDrift(ctx context.Context, arg RecordFeatureDriftParams) error
	// ============================================================
	// Monitoring
	// ============================================================
	RecordMonitoringMetric(ctx context.Context, arg RecordMonitoringMetricParams) error
	RollbackDeployment(ctx context.Context, arg RollbackDeploymentParams) error
	SetActiveModel(ctx context.Context, arg SetActiveModelParams) error
	SubmitFeedback(ctx context.Context, arg SubmitFeedbackParams) (string, error)
	UpdateDeploymentCanary(ctx context.Context, arg UpdateDeploymentCanaryParams) error
	UpdateDeploymentStatus(ctx context.Context, arg UpdateDeploymentStatusParams) error
	UpdateEvalRunResults(ctx context.Context, arg UpdateEvalRunResultsParams) error
	UpdateModelVersionStatus(ctx context.Context, arg UpdateModelVersionStatusParams) error
	UpdateTrainingRunCompleted(ctx context.Context, arg UpdateTrainingRunCompletedParams) error
	UpdateTrainingRunMetrics(ctx context.Context, arg UpdateTrainingRunMetricsParams) error
	UpdateTrainingRunStatus(ctx context.Context, arg UpdateTrainingRunStatusParams) error
}

var _ Querier = (*Queries)(nil)

